/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bareSkinDashboard;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import menu.menuBahan;
/**
 *
 * @author user
 */
public class menuDashboardAdmin1 extends javax.swing.JFrame{

    /**
     * Creates new form template
     */
    
    private JLabel activeButton = null;
    
    public menuDashboardAdmin1() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        activeButton = tDashboard;
        
        pn_utama.removeAll();
        pn_utama.add(new menu.menuVarian());
        pn_utama.repaint();
        pn_utama.revalidate();
        iDashboardT.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_kiri = new custom.PanelCustom();
        jLabel2 = new javax.swing.JLabel();
        pnDashboard = new custom.PanelCustom();
        tDashboard = new javax.swing.JLabel();
        Kdashboard = new custom.PanelCustom();
        iDashboardT = new javax.swing.JLabel();
        iDashboardG = new javax.swing.JLabel();
        iDashboardH = new javax.swing.JLabel();
        pnProduct = new custom.PanelCustom();
        tProduct = new javax.swing.JLabel();
        Kproduct = new custom.PanelCustom();
        iProductG = new javax.swing.JLabel();
        iProductT = new javax.swing.JLabel();
        iProductH = new javax.swing.JLabel();
        pnMember = new custom.PanelCustom();
        tMember = new javax.swing.JLabel();
        Kmember = new custom.PanelCustom();
        iMemberG = new javax.swing.JLabel();
        iMemberT = new javax.swing.JLabel();
        iMemberH = new javax.swing.JLabel();
        pnKaryawan = new custom.PanelCustom();
        tKaryawan = new javax.swing.JLabel();
        Kkaryawan = new custom.PanelCustom();
        iKaryawanG = new javax.swing.JLabel();
        iKaryawanT = new javax.swing.JLabel();
        iKaryawanH = new javax.swing.JLabel();
        pnPenjualan = new custom.PanelCustom();
        tPenjualan = new javax.swing.JLabel();
        Kpenjualan = new custom.PanelCustom();
        iPenjualanG = new javax.swing.JLabel();
        iPenjualanT = new javax.swing.JLabel();
        iPenjualanH = new javax.swing.JLabel();
        pnPembelian = new custom.PanelCustom();
        tPembelian = new javax.swing.JLabel();
        Kpembelian = new custom.PanelCustom();
        iPembelianG = new javax.swing.JLabel();
        iPembelianT = new javax.swing.JLabel();
        iPembelianH = new javax.swing.JLabel();
        pnLaporan = new custom.PanelCustom();
        tLaporan = new javax.swing.JLabel();
        Klaporan = new custom.PanelCustom();
        iLaporanG = new javax.swing.JLabel();
        iLaporanT = new javax.swing.JLabel();
        iLaporanH = new javax.swing.JLabel();
        pnLogout = new custom.PanelCustom();
        tLogout = new javax.swing.JLabel();
        Klogout = new custom.PanelCustom();
        iLogoutG = new javax.swing.JLabel();
        iLogoutT = new javax.swing.JLabel();
        iLogoutH = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pn_kiri.setBackground(new java.awt.Color(221, 136, 207));
        pn_kiri.setRoundBottomRight(100);
        pn_kiri.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/BS logo 100px (1).png"))); // NOI18N
        pn_kiri.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        pnDashboard.setBackground(new java.awt.Color(75, 22, 76));
        pnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        pnDashboard.setRoundBottomLeft(10);
        pnDashboard.setRoundBottomRight(40);
        pnDashboard.setRoundTopLeft(10);
        pnDashboard.setRoundTopRight(10);
        pnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnDashboardMouseExited(evt);
            }
        });
        pnDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tDashboard.setBackground(new java.awt.Color(245, 245, 245));
        tDashboard.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        tDashboard.setForeground(new java.awt.Color(245, 245, 245));
        tDashboard.setText("Dashboard");
        pnDashboard.add(tDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        Kdashboard.setBackground(new java.awt.Color(221, 136, 207));
        Kdashboard.setRoundBottomLeft(10);
        Kdashboard.setRoundBottomRight(10);
        Kdashboard.setRoundTopLeft(10);
        Kdashboard.setRoundTopRight(10);

        javax.swing.GroupLayout KdashboardLayout = new javax.swing.GroupLayout(Kdashboard);
        Kdashboard.setLayout(KdashboardLayout);
        KdashboardLayout.setHorizontalGroup(
            KdashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        KdashboardLayout.setVerticalGroup(
            KdashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        pnDashboard.add(Kdashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 6, -1, -1));

        iDashboardT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Dashboard T (1).png"))); // NOI18N
        pnDashboard.add(iDashboardT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 18, -1, -1));

        iDashboardG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Dashboard G (1).png"))); // NOI18N
        pnDashboard.add(iDashboardG, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 18, -1, -1));

        iDashboardH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Dashboard H.png"))); // NOI18N
        pnDashboard.add(iDashboardH, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 18, -1, -1));

        pn_kiri.add(pnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 240, 70));

        pnProduct.setBackground(new java.awt.Color(221, 136, 207));
        pnProduct.setRoundBottomLeft(10);
        pnProduct.setRoundBottomRight(40);
        pnProduct.setRoundTopLeft(10);
        pnProduct.setRoundTopRight(10);
        pnProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnProductMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnProductMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnProductMouseExited(evt);
            }
        });
        pnProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tProduct.setBackground(new java.awt.Color(75, 22, 76));
        tProduct.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        tProduct.setForeground(new java.awt.Color(75, 22, 76));
        tProduct.setText("Product");
        pnProduct.add(tProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        Kproduct.setBackground(new java.awt.Color(221, 136, 207));
        Kproduct.setRoundBottomLeft(10);
        Kproduct.setRoundBottomRight(10);
        Kproduct.setRoundTopLeft(10);
        Kproduct.setRoundTopRight(10);

        javax.swing.GroupLayout KproductLayout = new javax.swing.GroupLayout(Kproduct);
        Kproduct.setLayout(KproductLayout);
        KproductLayout.setHorizontalGroup(
            KproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        KproductLayout.setVerticalGroup(
            KproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        pnProduct.add(Kproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 6, -1, 60));

        iProductG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Product G.png"))); // NOI18N
        pnProduct.add(iProductG, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        iProductT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Product T.png"))); // NOI18N
        pnProduct.add(iProductT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        iProductH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Product H.png"))); // NOI18N
        pnProduct.add(iProductH, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        pn_kiri.add(pnProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 240, 70));

        pnMember.setBackground(new java.awt.Color(221, 136, 207));
        pnMember.setRoundBottomLeft(10);
        pnMember.setRoundBottomRight(40);
        pnMember.setRoundTopLeft(10);
        pnMember.setRoundTopRight(10);
        pnMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnMemberMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnMemberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnMemberMouseExited(evt);
            }
        });
        pnMember.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tMember.setBackground(new java.awt.Color(245, 245, 245));
        tMember.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        tMember.setForeground(new java.awt.Color(75, 22, 76));
        tMember.setText("Member");
        pnMember.add(tMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 17, -1, -1));

        Kmember.setBackground(new java.awt.Color(221, 136, 207));
        Kmember.setRoundBottomLeft(10);
        Kmember.setRoundBottomRight(10);
        Kmember.setRoundTopLeft(10);
        Kmember.setRoundTopRight(10);

        javax.swing.GroupLayout KmemberLayout = new javax.swing.GroupLayout(Kmember);
        Kmember.setLayout(KmemberLayout);
        KmemberLayout.setHorizontalGroup(
            KmemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        KmemberLayout.setVerticalGroup(
            KmemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        pnMember.add(Kmember, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 6, -1, -1));

        iMemberG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Member G (1).png"))); // NOI18N
        pnMember.add(iMemberG, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        iMemberT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Member T.png"))); // NOI18N
        pnMember.add(iMemberT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        iMemberH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Member H (1).png"))); // NOI18N
        pnMember.add(iMemberH, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        pn_kiri.add(pnMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 240, 70));

        pnKaryawan.setBackground(new java.awt.Color(221, 136, 207));
        pnKaryawan.setRoundBottomLeft(10);
        pnKaryawan.setRoundBottomRight(40);
        pnKaryawan.setRoundTopLeft(10);
        pnKaryawan.setRoundTopRight(10);
        pnKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnKaryawanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnKaryawanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnKaryawanMouseExited(evt);
            }
        });
        pnKaryawan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tKaryawan.setBackground(new java.awt.Color(245, 245, 245));
        tKaryawan.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        tKaryawan.setForeground(new java.awt.Color(75, 22, 76));
        tKaryawan.setText("Karyawan");
        pnKaryawan.add(tKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 16, -1, -1));

        Kkaryawan.setBackground(new java.awt.Color(221, 136, 207));
        Kkaryawan.setRoundBottomLeft(10);
        Kkaryawan.setRoundBottomRight(10);
        Kkaryawan.setRoundTopLeft(10);
        Kkaryawan.setRoundTopRight(10);

        javax.swing.GroupLayout KkaryawanLayout = new javax.swing.GroupLayout(Kkaryawan);
        Kkaryawan.setLayout(KkaryawanLayout);
        KkaryawanLayout.setHorizontalGroup(
            KkaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        KkaryawanLayout.setVerticalGroup(
            KkaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        pnKaryawan.add(Kkaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 6, -1, -1));

        iKaryawanG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Karyawan G.png"))); // NOI18N
        pnKaryawan.add(iKaryawanG, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        iKaryawanT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Karyawan T.png"))); // NOI18N
        pnKaryawan.add(iKaryawanT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        iKaryawanH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Member H.png"))); // NOI18N
        pnKaryawan.add(iKaryawanH, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        pn_kiri.add(pnKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 240, 70));

        pnPenjualan.setBackground(new java.awt.Color(221, 136, 207));
        pnPenjualan.setRoundBottomLeft(10);
        pnPenjualan.setRoundBottomRight(40);
        pnPenjualan.setRoundTopLeft(10);
        pnPenjualan.setRoundTopRight(10);
        pnPenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnPenjualanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnPenjualanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnPenjualanMouseExited(evt);
            }
        });
        pnPenjualan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tPenjualan.setBackground(new java.awt.Color(245, 245, 245));
        tPenjualan.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        tPenjualan.setForeground(new java.awt.Color(75, 22, 76));
        tPenjualan.setText("Penjualan");
        pnPenjualan.add(tPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 18, -1, -1));

        Kpenjualan.setBackground(new java.awt.Color(221, 136, 207));
        Kpenjualan.setRoundBottomLeft(10);
        Kpenjualan.setRoundBottomRight(10);
        Kpenjualan.setRoundTopLeft(10);
        Kpenjualan.setRoundTopRight(10);

        javax.swing.GroupLayout KpenjualanLayout = new javax.swing.GroupLayout(Kpenjualan);
        Kpenjualan.setLayout(KpenjualanLayout);
        KpenjualanLayout.setHorizontalGroup(
            KpenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        KpenjualanLayout.setVerticalGroup(
            KpenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        pnPenjualan.add(Kpenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 6, -1, -1));

        iPenjualanG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Penjualan G (1).png"))); // NOI18N
        pnPenjualan.add(iPenjualanG, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        iPenjualanT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Penjualan T.png"))); // NOI18N
        pnPenjualan.add(iPenjualanT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        iPenjualanH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Penjualan H.png"))); // NOI18N
        pnPenjualan.add(iPenjualanH, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        pn_kiri.add(pnPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 240, 70));

        pnPembelian.setBackground(new java.awt.Color(221, 136, 207));
        pnPembelian.setRoundBottomLeft(10);
        pnPembelian.setRoundBottomRight(40);
        pnPembelian.setRoundTopLeft(10);
        pnPembelian.setRoundTopRight(10);
        pnPembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnPembelianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnPembelianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnPembelianMouseExited(evt);
            }
        });
        pnPembelian.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tPembelian.setBackground(new java.awt.Color(245, 245, 245));
        tPembelian.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        tPembelian.setForeground(new java.awt.Color(75, 22, 76));
        tPembelian.setText("Pembelian");
        pnPembelian.add(tPembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 18, -1, -1));

        Kpembelian.setBackground(new java.awt.Color(221, 136, 207));
        Kpembelian.setRoundBottomLeft(10);
        Kpembelian.setRoundBottomRight(10);
        Kpembelian.setRoundTopLeft(10);
        Kpembelian.setRoundTopRight(10);

        javax.swing.GroupLayout KpembelianLayout = new javax.swing.GroupLayout(Kpembelian);
        Kpembelian.setLayout(KpembelianLayout);
        KpembelianLayout.setHorizontalGroup(
            KpembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        KpembelianLayout.setVerticalGroup(
            KpembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        pnPembelian.add(Kpembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 6, -1, -1));

        iPembelianG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pembelian G (1).png"))); // NOI18N
        pnPembelian.add(iPembelianG, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        iPembelianT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pembelian T.png"))); // NOI18N
        pnPembelian.add(iPembelianT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        iPembelianH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pembelian H.png"))); // NOI18N
        pnPembelian.add(iPembelianH, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        pn_kiri.add(pnPembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 240, 70));

        pnLaporan.setBackground(new java.awt.Color(221, 136, 207));
        pnLaporan.setRoundBottomLeft(10);
        pnLaporan.setRoundBottomRight(40);
        pnLaporan.setRoundTopLeft(10);
        pnLaporan.setRoundTopRight(10);
        pnLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnLaporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnLaporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnLaporanMouseExited(evt);
            }
        });
        pnLaporan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tLaporan.setBackground(new java.awt.Color(245, 245, 245));
        tLaporan.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        tLaporan.setForeground(new java.awt.Color(75, 22, 76));
        tLaporan.setText("Laporan");
        pnLaporan.add(tLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 17, -1, -1));

        Klaporan.setBackground(new java.awt.Color(221, 136, 207));
        Klaporan.setRoundBottomLeft(10);
        Klaporan.setRoundBottomRight(10);
        Klaporan.setRoundTopLeft(10);
        Klaporan.setRoundTopRight(10);

        javax.swing.GroupLayout KlaporanLayout = new javax.swing.GroupLayout(Klaporan);
        Klaporan.setLayout(KlaporanLayout);
        KlaporanLayout.setHorizontalGroup(
            KlaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        KlaporanLayout.setVerticalGroup(
            KlaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        pnLaporan.add(Klaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 6, -1, -1));

        iLaporanG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Laporan G (1).png"))); // NOI18N
        pnLaporan.add(iLaporanG, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        iLaporanT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Laporan T (1).png"))); // NOI18N
        pnLaporan.add(iLaporanT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        iLaporanH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Laporan H.png"))); // NOI18N
        pnLaporan.add(iLaporanH, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        pn_kiri.add(pnLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 690, 240, 70));

        pnLogout.setBackground(new java.awt.Color(221, 136, 207));
        pnLogout.setRoundBottomLeft(10);
        pnLogout.setRoundBottomRight(40);
        pnLogout.setRoundTopLeft(10);
        pnLogout.setRoundTopRight(10);
        pnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnLogoutMouseExited(evt);
            }
        });
        pnLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tLogout.setBackground(new java.awt.Color(245, 245, 245));
        tLogout.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        tLogout.setForeground(new java.awt.Color(75, 22, 76));
        tLogout.setText("Log Out");
        pnLogout.add(tLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 17, -1, -1));

        Klogout.setBackground(new java.awt.Color(221, 136, 207));
        Klogout.setRoundBottomLeft(10);
        Klogout.setRoundBottomRight(10);
        Klogout.setRoundTopLeft(10);
        Klogout.setRoundTopRight(10);

        javax.swing.GroupLayout KlogoutLayout = new javax.swing.GroupLayout(Klogout);
        Klogout.setLayout(KlogoutLayout);
        KlogoutLayout.setHorizontalGroup(
            KlogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        KlogoutLayout.setVerticalGroup(
            KlogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        pnLogout.add(Klogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 6, -1, -1));

        iLogoutG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Logout G (2).png"))); // NOI18N
        pnLogout.add(iLogoutG, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        iLogoutT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Logout T (1).png"))); // NOI18N
        pnLogout.add(iLogoutT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        iLogoutH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Logout H.png"))); // NOI18N
        pnLogout.add(iLogoutH, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        pn_kiri.add(pnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 930, 240, 70));

        getContentPane().add(pn_kiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 1020));

        jPanel1.setBackground(new java.awt.Color(248, 231, 246));

        pn_utama.setBackground(new java.awt.Color(248, 231, 246));
        pn_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(pn_utama, javax.swing.GroupLayout.PREFERRED_SIZE, 1571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pn_utama, javax.swing.GroupLayout.PREFERRED_SIZE, 971, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1730, 1020));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnProductMouseClicked
        resetButtonStyles();
        pnProduct.setBackground(new Color(75,22,76));
        tProduct.setForeground(new Color(245,245,245));
        iProductG.setVisible(false);
        iProductT.setVisible(true);
        Kproduct.setBackground(new Color(221,136,207));
        
        pn_utama.removeAll();
        pn_utama.add(new menu.menuBahan());
        pn_utama.repaint();
        pn_utama.revalidate();
        
        activeButton = tProduct;
    }//GEN-LAST:event_pnProductMouseClicked

    private void pnDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDashboardMouseClicked
        resetButtonStyles();
        pnDashboard.setBackground(new Color(75,22,76));
        tDashboard.setForeground(new Color(245,245,245));
        iDashboardG.setVisible(false);
        iDashboardT.setVisible(true);
        Kdashboard.setBackground(new Color(221,136,207));
        
        pn_utama.removeAll();
        pn_utama.add(new menu.menuVarian());
        pn_utama.repaint();
        pn_utama.revalidate();
        
        activeButton = tDashboard;
    }//GEN-LAST:event_pnDashboardMouseClicked

    private void pnProductMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnProductMouseEntered
        if (activeButton != tProduct) { 
        Kproduct.setBackground(new Color(75,23,107));
        pnProduct.setBackground(new Color(245,245,245));
        iProductT.setVisible(false);
        iProductG.setVisible(false);
        iProductH.setVisible(true);
        }
    }//GEN-LAST:event_pnProductMouseEntered

    private void pnProductMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnProductMouseExited
        if (activeButton != tProduct) { 
        pnProduct.setBackground(new Color(221,136,207));
        tProduct.setForeground(new Color(75,22,76));
        iProductT.setVisible(false);
        iProductG.setVisible(true);
        Kproduct.setBackground(new Color(221,136,207));
        }
    }//GEN-LAST:event_pnProductMouseExited

    private void pnDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDashboardMouseEntered
        if (activeButton != tDashboard) { 
        Kdashboard.setBackground(new Color(75,23,107));
        pnDashboard.setBackground(new Color(245,245,245));
        iDashboardT.setVisible(false);
        iDashboardG.setVisible(false);
        iDashboardH.setVisible(true);
        }
    }//GEN-LAST:event_pnDashboardMouseEntered

    private void pnDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDashboardMouseExited
        if (activeButton != tDashboard) { 
        pnDashboard.setBackground(new Color(221,136,207));
        tDashboard.setForeground(new Color(75,22,76));
        iDashboardT.setVisible(false);
        iDashboardG.setVisible(true);
        Kdashboard.setBackground(new Color(221,136,207));
        }
    }//GEN-LAST:event_pnDashboardMouseExited

    private void pnMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMemberMouseClicked
        resetButtonStyles();
        pnMember.setBackground(new Color(75,22,76));
        tMember.setForeground(new Color(245,245,245));
        iMemberG.setVisible(false);
        iMemberT.setVisible(true);
        Kmember.setBackground(new Color(221,136,207));
        
        pn_utama.removeAll();
        pn_utama.add(new menu.menuBahan());
        pn_utama.repaint();
        pn_utama.revalidate();
        
        activeButton = tMember;
    }//GEN-LAST:event_pnMemberMouseClicked

    private void pnMemberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMemberMouseEntered
        if (activeButton != tMember) { 
        Kmember.setBackground(new Color(75,23,107));
        pnMember.setBackground(new Color(245,245,245));
        iMemberT.setVisible(false);
        iMemberG.setVisible(false);
        iMemberH.setVisible(true);
        }
    }//GEN-LAST:event_pnMemberMouseEntered

    private void pnMemberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMemberMouseExited
        if (activeButton != tMember) { 
        pnMember.setBackground(new Color(221,136,207));
        tMember.setForeground(new Color(75,22,76));
        Kmember.setBackground(new Color(221,136,207));
        iMemberT.setVisible(false);
        iMemberG.setVisible(true);
        }
    }//GEN-LAST:event_pnMemberMouseExited

    private void pnKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnKaryawanMouseClicked
        resetButtonStyles();
        pnKaryawan.setBackground(new Color(75,22,76));
        tKaryawan.setForeground(new Color(245,245,245));
        iKaryawanG.setVisible(false);
        iKaryawanT.setVisible(true);
        Kkaryawan.setBackground(new Color(221,136,207));
        
        pn_utama.removeAll();
        pn_utama.add(new menu.menuBahan());
        pn_utama.repaint();
        pn_utama.revalidate();
        
        activeButton = tKaryawan;
    }//GEN-LAST:event_pnKaryawanMouseClicked

    private void pnKaryawanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnKaryawanMouseEntered
        if (activeButton != tKaryawan) { 
        Kkaryawan.setBackground(new Color(75,23,107));
        pnKaryawan.setBackground(new Color(245,245,245));
        iKaryawanT.setVisible(false);
        iKaryawanG.setVisible(false);
        iKaryawanH.setVisible(true);
        }
    }//GEN-LAST:event_pnKaryawanMouseEntered

    private void pnKaryawanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnKaryawanMouseExited
        if (activeButton != tKaryawan) { 
        pnKaryawan.setBackground(new Color(221,136,207));
        tKaryawan.setForeground(new Color(75,22,76));
        Kkaryawan.setBackground(new Color(221,136,207));
        iKaryawanT.setVisible(false);
        iKaryawanG.setVisible(true);
        }
    }//GEN-LAST:event_pnKaryawanMouseExited

    private void pnPenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnPenjualanMouseClicked
        resetButtonStyles();
        pnPenjualan.setBackground(new Color(75,22,76));
        tPenjualan.setForeground(new Color(245,245,245));
        iPenjualanG.setVisible(false);
        iPenjualanT.setVisible(true);
        Kpenjualan.setBackground(new Color(221,136,207));
        
        pn_utama.removeAll();
        pn_utama.add(new menu.menuBahan());
        pn_utama.repaint();
        pn_utama.revalidate();
        
        activeButton = tPenjualan;
    }//GEN-LAST:event_pnPenjualanMouseClicked

    private void pnPenjualanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnPenjualanMouseEntered
        if (activeButton != tPenjualan) { 
        Kpenjualan.setBackground(new Color(75,23,107));
        pnPenjualan.setBackground(new Color(245,245,245));
        iPenjualanT.setVisible(false);
        iPenjualanG.setVisible(false);
        iPenjualanH.setVisible(true);
        }
    }//GEN-LAST:event_pnPenjualanMouseEntered

    private void pnPenjualanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnPenjualanMouseExited
        if (activeButton != tPenjualan) { 
        pnPenjualan.setBackground(new Color(221,136,207));
        tPenjualan.setForeground(new Color(75,22,76));
        Kpenjualan.setBackground(new Color(221,136,207));
        iPenjualanT.setVisible(false);
        iPenjualanG.setVisible(true);
        }
    }//GEN-LAST:event_pnPenjualanMouseExited

    private void pnPembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnPembelianMouseClicked
        resetButtonStyles();
        pnPembelian.setBackground(new Color(75,22,76));
        tPembelian.setForeground(new Color(245,245,245));
        iPembelianG.setVisible(false);
        iPembelianT.setVisible(true);
        Kpembelian.setBackground(new Color(221,136,207));
        
        pn_utama.removeAll();
        pn_utama.add(new menu.menuBahan());
        pn_utama.repaint();
        pn_utama.revalidate();
        
        activeButton = tPembelian;
    }//GEN-LAST:event_pnPembelianMouseClicked

    private void pnPembelianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnPembelianMouseEntered
        if (activeButton != tPembelian) { 
        Kpembelian.setBackground(new Color(75,23,107));
        pnPembelian.setBackground(new Color(245,245,245));
        iPembelianT.setVisible(false);
        iPembelianG.setVisible(false);
        iPembelianH.setVisible(true);
        }
    }//GEN-LAST:event_pnPembelianMouseEntered

    private void pnPembelianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnPembelianMouseExited
        if (activeButton != tPembelian) { 
        pnPembelian.setBackground(new Color(221,136,207));
        tPembelian.setForeground(new Color(75,22,76));
        Kpembelian.setBackground(new Color(221,136,207));
        iPembelianT.setVisible(false);
        iPembelianG.setVisible(true);
        }
    }//GEN-LAST:event_pnPembelianMouseExited

    private void pnLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnLaporanMouseClicked
        resetButtonStyles();
        pnLaporan.setBackground(new Color(75,22,76));
        tLaporan.setForeground(new Color(245,245,245));
        iLaporanG.setVisible(false);
        iLaporanT.setVisible(true);
        Klaporan.setBackground(new Color(221,136,207));

        pn_utama.removeAll();
        pn_utama.add(new menu.menuBahan());
        pn_utama.repaint();
        pn_utama.revalidate();
        
        activeButton = tLaporan;
    }//GEN-LAST:event_pnLaporanMouseClicked

    private void pnLaporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnLaporanMouseEntered
        if (activeButton != tLaporan) { 
        Klaporan.setBackground(new Color(75,23,107));
        pnLaporan.setBackground(new Color(245,245,245));
        iLaporanT.setVisible(false);
        iLaporanG.setVisible(false);
        iLaporanH.setVisible(true);
        }
    }//GEN-LAST:event_pnLaporanMouseEntered

    private void pnLaporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnLaporanMouseExited
        if (activeButton != tLaporan) { 
        pnLaporan.setBackground(new Color(221,136,207));
        tLaporan.setForeground(new Color(75,22,76));
        Klaporan.setBackground(new Color(221,136,207));
        iLaporanT.setVisible(false);
        iLaporanG.setVisible(true);
        }
    }//GEN-LAST:event_pnLaporanMouseExited

    private void pnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnLogoutMouseClicked
        resetButtonStyles();
        pnLogout.setBackground(new Color(75,22,76));
        tLogout.setForeground(new Color(245,245,245));
        iLogoutG.setVisible(false);
        iLogoutT.setVisible(true);
        Klogout.setBackground(new Color(221,136,207));

        pn_utama.removeAll();
        pn_utama.add(new menu.menuBahan());
        pn_utama.repaint();
        pn_utama.revalidate();
        
        activeButton = tLogout;
    }//GEN-LAST:event_pnLogoutMouseClicked

    private void pnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnLogoutMouseEntered
        if (activeButton != tLogout) { 
        Klogout.setBackground(new Color(75,23,107));
        pnLogout.setBackground(new Color(245,245,245));
        iLogoutT.setVisible(false);
        iLogoutG.setVisible(false);
        iLogoutH.setVisible(true);
        }
    }//GEN-LAST:event_pnLogoutMouseEntered

    private void pnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnLogoutMouseExited
        if (activeButton != tLogout) { 
        pnLogout.setBackground(new Color(221,136,207));
        tLogout.setForeground(new Color(75,22,76));
        Klogout.setBackground(new Color(221,136,207));
        iLogoutT.setVisible(false);
        iLogoutG.setVisible(true);
        }
    }//GEN-LAST:event_pnLogoutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuDashboardAdmin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuDashboardAdmin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuDashboardAdmin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuDashboardAdmin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuDashboardAdmin1().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private custom.PanelCustom Kdashboard;
    private custom.PanelCustom Kkaryawan;
    private custom.PanelCustom Klaporan;
    private custom.PanelCustom Klogout;
    private custom.PanelCustom Kmember;
    private custom.PanelCustom Kpembelian;
    private custom.PanelCustom Kpenjualan;
    private custom.PanelCustom Kproduct;
    private javax.swing.JLabel iDashboardG;
    private javax.swing.JLabel iDashboardH;
    private javax.swing.JLabel iDashboardT;
    private javax.swing.JLabel iKaryawanG;
    private javax.swing.JLabel iKaryawanH;
    private javax.swing.JLabel iKaryawanT;
    private javax.swing.JLabel iLaporanG;
    private javax.swing.JLabel iLaporanH;
    private javax.swing.JLabel iLaporanT;
    private javax.swing.JLabel iLogoutG;
    private javax.swing.JLabel iLogoutH;
    private javax.swing.JLabel iLogoutT;
    private javax.swing.JLabel iMemberG;
    private javax.swing.JLabel iMemberH;
    private javax.swing.JLabel iMemberT;
    private javax.swing.JLabel iPembelianG;
    private javax.swing.JLabel iPembelianH;
    private javax.swing.JLabel iPembelianT;
    private javax.swing.JLabel iPenjualanG;
    private javax.swing.JLabel iPenjualanH;
    private javax.swing.JLabel iPenjualanT;
    private javax.swing.JLabel iProductG;
    private javax.swing.JLabel iProductH;
    private javax.swing.JLabel iProductT;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private custom.PanelCustom pnDashboard;
    private custom.PanelCustom pnKaryawan;
    private custom.PanelCustom pnLaporan;
    private custom.PanelCustom pnLogout;
    private custom.PanelCustom pnMember;
    private custom.PanelCustom pnPembelian;
    private custom.PanelCustom pnPenjualan;
    private custom.PanelCustom pnProduct;
    private custom.PanelCustom pn_kiri;
    private javax.swing.JPanel pn_utama;
    private javax.swing.JLabel tDashboard;
    private javax.swing.JLabel tKaryawan;
    private javax.swing.JLabel tLaporan;
    private javax.swing.JLabel tLogout;
    private javax.swing.JLabel tMember;
    private javax.swing.JLabel tPembelian;
    private javax.swing.JLabel tPenjualan;
    private javax.swing.JLabel tProduct;
    // End of variables declaration//GEN-END:variables
    
    private void resetButtonStyles() {
    // Reset warna tombol lain di sini
    pnDashboard.setBackground(new Color(221,136,207));
    tDashboard.setForeground(new Color(75,22,76));
    iDashboardT.setVisible(false);
    iDashboardG.setVisible(true);

    pnProduct.setBackground(new Color(221,136,207));
    tProduct.setForeground(new Color(75,22,76));
    iProductT.setVisible(false);
    iProductG.setVisible(true);
    
    pnMember.setBackground(new Color(221,136,207));
    tMember.setForeground(new Color(75,22,76));
    iMemberT.setVisible(false);
    iMemberG.setVisible(true);
    
    pnKaryawan.setBackground(new Color(221,136,207));
    tKaryawan.setForeground(new Color(75,22,76));
    iKaryawanT.setVisible(false);
    iKaryawanG.setVisible(true);
    
    pnPenjualan.setBackground(new Color(221,136,207));
    tPenjualan.setForeground(new Color(75,22,76));
    iPenjualanT.setVisible(false);
    iPenjualanG.setVisible(true);
    
    pnPembelian.setBackground(new Color(221,136,207));
    tPembelian.setForeground(new Color(75,22,76));
    iPembelianT.setVisible(false);
    iPembelianG.setVisible(true);
    
    pnLaporan.setBackground(new Color(221,136,207));
    tLaporan.setForeground(new Color(75,22,76));
    iLaporanT.setVisible(false);
    iLaporanG.setVisible(true);
    
    pnLogout.setBackground(new Color(221,136,207));
    tLogout.setForeground(new Color(75,22,76));
    iLogoutT.setVisible(false);
    iLogoutG.setVisible(true);
    }
    
}
