/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bareSkinDashboard;

import javax.swing.JFrame;

/**
 *
 * @author user
 */
public class template extends javax.swing.JFrame{

    /**
     * Creates new form template
     */
    public template() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_kiri = new custom.PanelCustom();
        jLabel2 = new javax.swing.JLabel();
        pnDashboard = new custom.PanelCustom();
        jLabel1 = new javax.swing.JLabel();
        panelCustom2 = new custom.PanelCustom();
        jLabel9 = new javax.swing.JLabel();
        pnProduct = new custom.PanelCustom();
        jLabel3 = new javax.swing.JLabel();
        panelCustom5 = new custom.PanelCustom();
        pnMember = new custom.PanelCustom();
        jLabel4 = new javax.swing.JLabel();
        panelCustom7 = new custom.PanelCustom();
        pnKaryawan = new custom.PanelCustom();
        jLabel5 = new javax.swing.JLabel();
        panelCustom9 = new custom.PanelCustom();
        pnPenjualan = new custom.PanelCustom();
        jLabel6 = new javax.swing.JLabel();
        panelCustom11 = new custom.PanelCustom();
        pnPembelian = new custom.PanelCustom();
        jLabel7 = new javax.swing.JLabel();
        panelCustom13 = new custom.PanelCustom();
        pnLaporan = new custom.PanelCustom();
        jLabel8 = new javax.swing.JLabel();
        panelCustom15 = new custom.PanelCustom();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pn_kiri.setBackground(new java.awt.Color(221, 136, 207));
        pn_kiri.setRoundBottomRight(100);
        pn_kiri.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/BS logo.png"))); // NOI18N
        pn_kiri.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        pnDashboard.setBackground(new java.awt.Color(75, 22, 76));
        pnDashboard.setRoundBottomLeft(10);
        pnDashboard.setRoundBottomRight(40);
        pnDashboard.setRoundTopLeft(10);
        pnDashboard.setRoundTopRight(10);

        jLabel1.setBackground(new java.awt.Color(245, 245, 245));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 245, 245));
        jLabel1.setText("Dashboard");

        panelCustom2.setBackground(new java.awt.Color(221, 136, 207));
        panelCustom2.setRoundBottomLeft(10);
        panelCustom2.setRoundBottomRight(10);
        panelCustom2.setRoundTopLeft(10);
        panelCustom2.setRoundTopRight(10);

        javax.swing.GroupLayout panelCustom2Layout = new javax.swing.GroupLayout(panelCustom2);
        panelCustom2.setLayout(panelCustom2Layout);
        panelCustom2Layout.setHorizontalGroup(
            panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        panelCustom2Layout.setVerticalGroup(
            panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Dashboard T.png"))); // NOI18N

        javax.swing.GroupLayout pnDashboardLayout = new javax.swing.GroupLayout(pnDashboard);
        pnDashboard.setLayout(pnDashboardLayout);
        pnDashboardLayout.setHorizontalGroup(
            pnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDashboardLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panelCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pnDashboardLayout.setVerticalGroup(
            pnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDashboardLayout.createSequentialGroup()
                .addGroup(pnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDashboardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnDashboardLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_kiri.add(pnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 260, 70));

        pnProduct.setBackground(new java.awt.Color(221, 136, 207));
        pnProduct.setRoundBottomLeft(10);
        pnProduct.setRoundBottomRight(40);
        pnProduct.setRoundTopLeft(10);
        pnProduct.setRoundTopRight(10);

        jLabel3.setBackground(new java.awt.Color(75, 22, 76));
        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(75, 22, 76));
        jLabel3.setText("Product");

        panelCustom5.setBackground(new java.awt.Color(221, 136, 207));
        panelCustom5.setRoundBottomLeft(10);
        panelCustom5.setRoundBottomRight(10);
        panelCustom5.setRoundTopLeft(10);
        panelCustom5.setRoundTopRight(10);

        javax.swing.GroupLayout panelCustom5Layout = new javax.swing.GroupLayout(panelCustom5);
        panelCustom5.setLayout(panelCustom5Layout);
        panelCustom5Layout.setHorizontalGroup(
            panelCustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        panelCustom5Layout.setVerticalGroup(
            panelCustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnProductLayout = new javax.swing.GroupLayout(pnProduct);
        pnProduct.setLayout(pnProductLayout);
        pnProductLayout.setHorizontalGroup(
            pnProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnProductLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panelCustom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel3)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        pnProductLayout.setVerticalGroup(
            pnProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCustom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnProductLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(19, 19, 19))
        );

        pn_kiri.add(pnProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 260, 70));

        pnMember.setBackground(new java.awt.Color(221, 136, 207));
        pnMember.setRoundBottomLeft(10);
        pnMember.setRoundBottomRight(40);
        pnMember.setRoundTopLeft(10);
        pnMember.setRoundTopRight(10);

        jLabel4.setBackground(new java.awt.Color(245, 245, 245));
        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(75, 22, 76));
        jLabel4.setText("Member");

        panelCustom7.setBackground(new java.awt.Color(221, 136, 207));
        panelCustom7.setRoundBottomLeft(10);
        panelCustom7.setRoundBottomRight(10);
        panelCustom7.setRoundTopLeft(10);
        panelCustom7.setRoundTopRight(10);

        javax.swing.GroupLayout panelCustom7Layout = new javax.swing.GroupLayout(panelCustom7);
        panelCustom7.setLayout(panelCustom7Layout);
        panelCustom7Layout.setHorizontalGroup(
            panelCustom7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        panelCustom7Layout.setVerticalGroup(
            panelCustom7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnMemberLayout = new javax.swing.GroupLayout(pnMember);
        pnMember.setLayout(pnMemberLayout);
        pnMemberLayout.setHorizontalGroup(
            pnMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMemberLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panelCustom7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jLabel4)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        pnMemberLayout.setVerticalGroup(
            pnMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMemberLayout.createSequentialGroup()
                .addGroup(pnMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMemberLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelCustom7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnMemberLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_kiri.add(pnMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 260, 70));

        pnKaryawan.setBackground(new java.awt.Color(221, 136, 207));
        pnKaryawan.setRoundBottomLeft(10);
        pnKaryawan.setRoundBottomRight(40);
        pnKaryawan.setRoundTopLeft(10);
        pnKaryawan.setRoundTopRight(10);

        jLabel5.setBackground(new java.awt.Color(245, 245, 245));
        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(75, 22, 76));
        jLabel5.setText("Karyawan");

        panelCustom9.setBackground(new java.awt.Color(221, 136, 207));
        panelCustom9.setRoundBottomLeft(10);
        panelCustom9.setRoundBottomRight(10);
        panelCustom9.setRoundTopLeft(10);
        panelCustom9.setRoundTopRight(10);

        javax.swing.GroupLayout panelCustom9Layout = new javax.swing.GroupLayout(panelCustom9);
        panelCustom9.setLayout(panelCustom9Layout);
        panelCustom9Layout.setHorizontalGroup(
            panelCustom9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        panelCustom9Layout.setVerticalGroup(
            panelCustom9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnKaryawanLayout = new javax.swing.GroupLayout(pnKaryawan);
        pnKaryawan.setLayout(pnKaryawanLayout);
        pnKaryawanLayout.setHorizontalGroup(
            pnKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnKaryawanLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panelCustom9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(59, 59, 59))
        );
        pnKaryawanLayout.setVerticalGroup(
            pnKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKaryawanLayout.createSequentialGroup()
                .addGroup(pnKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnKaryawanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelCustom9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnKaryawanLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_kiri.add(pnKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 260, 70));

        pnPenjualan.setBackground(new java.awt.Color(221, 136, 207));
        pnPenjualan.setRoundBottomLeft(10);
        pnPenjualan.setRoundBottomRight(40);
        pnPenjualan.setRoundTopLeft(10);
        pnPenjualan.setRoundTopRight(10);

        jLabel6.setBackground(new java.awt.Color(245, 245, 245));
        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(75, 22, 76));
        jLabel6.setText("Penjualan");

        panelCustom11.setBackground(new java.awt.Color(221, 136, 207));
        panelCustom11.setRoundBottomLeft(10);
        panelCustom11.setRoundBottomRight(10);
        panelCustom11.setRoundTopLeft(10);
        panelCustom11.setRoundTopRight(10);

        javax.swing.GroupLayout panelCustom11Layout = new javax.swing.GroupLayout(panelCustom11);
        panelCustom11.setLayout(panelCustom11Layout);
        panelCustom11Layout.setHorizontalGroup(
            panelCustom11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        panelCustom11Layout.setVerticalGroup(
            panelCustom11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnPenjualanLayout = new javax.swing.GroupLayout(pnPenjualan);
        pnPenjualan.setLayout(pnPenjualanLayout);
        pnPenjualanLayout.setHorizontalGroup(
            pnPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPenjualanLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panelCustom11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(58, 58, 58))
        );
        pnPenjualanLayout.setVerticalGroup(
            pnPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPenjualanLayout.createSequentialGroup()
                .addGroup(pnPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPenjualanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelCustom11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnPenjualanLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_kiri.add(pnPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 260, 70));

        pnPembelian.setBackground(new java.awt.Color(221, 136, 207));
        pnPembelian.setRoundBottomLeft(10);
        pnPembelian.setRoundBottomRight(40);
        pnPembelian.setRoundTopLeft(10);
        pnPembelian.setRoundTopRight(10);

        jLabel7.setBackground(new java.awt.Color(245, 245, 245));
        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(75, 22, 76));
        jLabel7.setText("Pembelian");

        panelCustom13.setBackground(new java.awt.Color(221, 136, 207));
        panelCustom13.setRoundBottomLeft(10);
        panelCustom13.setRoundBottomRight(10);
        panelCustom13.setRoundTopLeft(10);
        panelCustom13.setRoundTopRight(10);

        javax.swing.GroupLayout panelCustom13Layout = new javax.swing.GroupLayout(panelCustom13);
        panelCustom13.setLayout(panelCustom13Layout);
        panelCustom13Layout.setHorizontalGroup(
            panelCustom13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        panelCustom13Layout.setVerticalGroup(
            panelCustom13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnPembelianLayout = new javax.swing.GroupLayout(pnPembelian);
        pnPembelian.setLayout(pnPembelianLayout);
        pnPembelianLayout.setHorizontalGroup(
            pnPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPembelianLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panelCustom13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(52, 52, 52))
        );
        pnPembelianLayout.setVerticalGroup(
            pnPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPembelianLayout.createSequentialGroup()
                .addGroup(pnPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPembelianLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelCustom13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnPembelianLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_kiri.add(pnPembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 260, 70));

        pnLaporan.setBackground(new java.awt.Color(221, 136, 207));
        pnLaporan.setRoundBottomLeft(10);
        pnLaporan.setRoundBottomRight(40);
        pnLaporan.setRoundTopLeft(10);
        pnLaporan.setRoundTopRight(10);

        jLabel8.setBackground(new java.awt.Color(245, 245, 245));
        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(75, 22, 76));
        jLabel8.setText("Laporan");

        panelCustom15.setBackground(new java.awt.Color(221, 136, 207));
        panelCustom15.setRoundBottomLeft(10);
        panelCustom15.setRoundBottomRight(10);
        panelCustom15.setRoundTopLeft(10);
        panelCustom15.setRoundTopRight(10);

        javax.swing.GroupLayout panelCustom15Layout = new javax.swing.GroupLayout(panelCustom15);
        panelCustom15.setLayout(panelCustom15Layout);
        panelCustom15Layout.setHorizontalGroup(
            panelCustom15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        panelCustom15Layout.setVerticalGroup(
            panelCustom15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnLaporanLayout = new javax.swing.GroupLayout(pnLaporan);
        pnLaporan.setLayout(pnLaporanLayout);
        pnLaporanLayout.setHorizontalGroup(
            pnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLaporanLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panelCustom15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabel8)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        pnLaporanLayout.setVerticalGroup(
            pnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLaporanLayout.createSequentialGroup()
                .addGroup(pnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnLaporanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelCustom15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnLaporanLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_kiri.add(pnLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 750, 260, 70));

        getContentPane().add(pn_kiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 1020));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1690, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1690, 1020));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(template.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(template.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(template.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(template.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new template().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel5;
    private custom.PanelCustom panelCustom11;
    private custom.PanelCustom panelCustom13;
    private custom.PanelCustom panelCustom15;
    private custom.PanelCustom panelCustom2;
    private custom.PanelCustom panelCustom5;
    private custom.PanelCustom panelCustom7;
    private custom.PanelCustom panelCustom9;
    private custom.PanelCustom pnDashboard;
    private custom.PanelCustom pnKaryawan;
    private custom.PanelCustom pnLaporan;
    private custom.PanelCustom pnMember;
    private custom.PanelCustom pnPembelian;
    private custom.PanelCustom pnPenjualan;
    private custom.PanelCustom pnProduct;
    private custom.PanelCustom pn_kiri;
    // End of variables declaration//GEN-END:variables
}
