/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bareSkinMenu;

/**
 *
 * @author Amandaanisa
 */
import java.awt.Image;
import java.awt.Window;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.sourceforge.jbarcodebean.JBarcodeBean;

//import jnafilechooser.api.JnaFileChooser;
import net.sourceforge.jbarcodebean.model.AbstractBarcodeStrategy;
import net.sourceforge.jbarcodebean.model.Codabar;
import net.sourceforge.jbarcodebean.model.Code11;
import net.sourceforge.jbarcodebean.model.Code128;
import net.sourceforge.jbarcodebean.model.Code39;
import net.sourceforge.jbarcodebean.model.Code93;
import net.sourceforge.jbarcodebean.model.Ean13;
import net.sourceforge.jbarcodebean.model.Ean8;
import net.sourceforge.jbarcodebean.model.Interleaved25;
import net.sourceforge.jbarcodebean.model.MSI;

public class barcode extends javax.swing.JFrame {
    
    private BufferedImage image = null;

    public barcode(String idProduk) {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);

        if (lb_barcode != null) {
            // Pastikan barcode type sesuai pilihan
            String selectedType = "Code128"; // Bisa diganti nanti jika dari combo box
            AbstractBarcodeStrategy strategy = getCodeType(selectedType);

            if (strategy != null) {
                JBarcodeBean barcodeBean = new JBarcodeBean();
                barcodeBean.setCodeType(strategy);
                barcodeBean.setCode(idProduk);

                int barcodeWidth = 200;
                int barcodeHeight = 100;
                image = barcodeBean.draw(new BufferedImage(barcodeWidth, barcodeHeight, BufferedImage.TYPE_INT_RGB));

                //image = barcodeBean.draw(new BufferedImage(lb_barcode.getWidth(), lb_barcode.getHeight(), BufferedImage.TYPE_INT_RGB));
                ImageIcon iconBarcode = new ImageIcon(
                new ImageIcon(image).getImage().getScaledInstance(
                lb_barcode.getWidth(),
                lb_barcode.getHeight(),
                Image.SCALE_SMOOTH
            )
        );

        // Tampilkan barcode di label
        lb_barcode.setIcon(iconBarcode);


    //        JBarcodeBean barcodeBean = new JBarcodeBean();
    //    barcodeBean.setCodeType(new Code128()); // atau get dari combo box
    //    barcodeBean.setCode(idProduk);
    //
    //    int barcodeWidth = 200;
    //    int barcodeHeight = 100;
    //    BufferedImage image = barcodeBean.draw(new BufferedImage(barcodeWidth, barcodeHeight, BufferedImage.TYPE_INT_RGB));
    //
    //    ImageIcon iconBarcode = new ImageIcon(
    //        new ImageIcon(image).getImage().getScaledInstance(
    //            lb_barcode.getWidth(),
    //            lb_barcode.getHeight(),
    //            Image.SCALE_SMOOTH
    //        )
    //    );
    //
    //    lb_barcode.setIcon(iconBarcode);

            }

        }
    }
    private AbstractBarcodeStrategy getCodeType(String codeType){
    AbstractBarcodeStrategy mCodeType = null;
    switch (codeType){
        case "Code11":
            mCodeType = new Code11();
            break;
        case "Code93":
            mCodeType = new Code93();
            break;
        case "Code128":
            mCodeType = new Code128();
            break;
        case "Codabar":
            mCodeType = new Codabar();
            break;
        case "Code39":
            mCodeType = new Code39();
            break;
        case "Ean8":
            mCodeType = new Ean8();
            break;
        case "Ean13":
            mCodeType = new Ean13();
            break;
        case "Interleaved25":
            mCodeType = new Interleaved25();
            break;
        case "MSI":
            mCodeType = new MSI();
            break;
        default:
            mCodeType = null;
    }
    return mCodeType;
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbx_code = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnExport = new javax.swing.JButton();
        lb_barcode = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(248, 231, 246));

        jPanel1.setBackground(new java.awt.Color(248, 231, 246));

        cbx_code.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Code128", "Codebar", "Ean13" }));
        cbx_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_codeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tipe Barcode");

        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbx_code, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lb_barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_code, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(lb_barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_codeActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        //exportBarcode(image);

    }//GEN-LAST:event_btnExportActionPerformed
    
//    private boolean exportBarcode(BufferedImage imageBarcode) {
//    JFileChooser fileChooser = new JFileChooser(new File("C:\\Users\\Public")); // Lokasi awal aman
//    fileChooser.setDialogTitle("Simpan Barcode sebagai PNG");
//    fileChooser.setFileFilter(new FileNameExtensionFilter("PNG Images", "png"));

//    SwingUtilities.windowForComponent(this); // Tidak dipakai, bisa dihapus
//    int action = fileChooser.showSaveDialog(this);
//
//    if (action == JFileChooser.APPROVE_OPTION) {
//        File fileBarcode = fileChooser.getSelectedFile();
//        
//        // Tambahkan ".png" jika user tidak menulis ekstensi
//        if (!fileBarcode.getName().toLowerCase().endsWith(".png")) {
//            fileBarcode = new File(fileBarcode.getAbsolutePath() + ".png");
//        }
//
//        try {
//            ImageIO.write(imageBarcode, "png", fileBarcode);
//            return true; // Berhasil
//        } catch (IOException e) {
//            e.printStackTrace();
//            return false; // Gagal saat menyimpan
//        }
//    } else {
//        return false; // User klik Cancel
//    }
//}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(barcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(barcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(barcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(barcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            private String idProduk;
            public void run() {
                new barcode(idProduk).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JComboBox<String> cbx_code;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_barcode;
    // End of variables declaration//GEN-END:variables

   

        
    }

