/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bareSkinMenu;

import java.awt.Color;

/**
 *
 * @author LENOVO
 */
public class dashboardAdmin extends javax.swing.JPanel {

    /**
     * Creates new form transaksiPenjualan
     */
    public dashboardAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelView = new javax.swing.JPanel();
        panelCustom1 = new custom.PanelCustom();
        tNamaMenu1 = new javax.swing.JLabel();
        panelCustom2 = new custom.PanelCustom();
        tNamaMenu = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        panelMain.setLayout(new java.awt.CardLayout());

        panelView.setBackground(new java.awt.Color(248, 231, 246));
        panelView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCustom1.setBackground(new java.awt.Color(255, 255, 255));
        panelCustom1.setRoundBottomLeft(20);
        panelCustom1.setRoundBottomRight(20);
        panelCustom1.setRoundTopLeft(20);
        panelCustom1.setRoundTopRight(20);
        panelCustom1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tNamaMenu1.setBackground(new java.awt.Color(245, 245, 245));
        tNamaMenu1.setFont(new java.awt.Font("SansSerif", 1, 40)); // NOI18N
        tNamaMenu1.setForeground(new java.awt.Color(75, 22, 76));
        tNamaMenu1.setText("MENU DASHBOARD ADMIN");
        panelCustom1.add(tNamaMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, -1, -1));

        panelView.add(panelCustom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1600, 940));

        panelCustom2.setBackground(new java.awt.Color(255, 255, 255));
        panelCustom2.setRoundBottomLeft(20);
        panelCustom2.setRoundBottomRight(20);
        panelCustom2.setRoundTopLeft(20);
        panelCustom2.setRoundTopRight(20);
        panelCustom2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tNamaMenu.setBackground(new java.awt.Color(245, 245, 245));
        tNamaMenu.setFont(new java.awt.Font("SansSerif", 1, 40)); // NOI18N
        tNamaMenu.setForeground(new java.awt.Color(75, 22, 76));
        tNamaMenu.setText("MENU DASHBOARD");
        panelCustom2.add(tNamaMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        panelView.add(panelCustom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1600, 70));

        panelMain.add(panelView, "card2");

        add(panelMain, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private custom.PanelCustom panelCustom1;
    private custom.PanelCustom panelCustom2;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelView;
    private javax.swing.JLabel tNamaMenu;
    private javax.swing.JLabel tNamaMenu1;
    // End of variables declaration//GEN-END:variables
}
