/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bareSkinMenu;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import config.koneksi;

public class menuLaporan extends javax.swing.JPanel {
    
    private int halamanSaatIni = 1;
    private int dataPerHalaman = 14;
    private int totalPages;
    // private String id_user;
    private final Connection conn;
    
    
    public menuLaporan() {
        conn = koneksi.getConnection();
        initComponents();
        loadData();
        setTabelModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelViewPendapatan = new javax.swing.JPanel();
        pnMain = new custom.PanelCustom();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        iSearch = new javax.swing.JLabel();
        txtSearch = new custom.JTextFieldRounded();
        btnTambah = new rojerusan.RSMaterialButtonRectangle();
        btnTambah1 = new rojerusan.RSMaterialButtonRectangle();
        panelCustom2 = new custom.PanelCustom();
        panelCustom4 = new custom.PanelCustom();
        jLabel23 = new javax.swing.JLabel();
        panelCustom5 = new custom.PanelCustom();
        jLabel25 = new javax.swing.JLabel();
        panelCustom6 = new custom.PanelCustom();
        jLabel26 = new javax.swing.JLabel();
        panelCustom7 = new custom.PanelCustom();
        jLabel27 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtIdMember = new custom.JTextFieldRounded();
        txtIdMember1 = new custom.JTextFieldRounded();
        btnTambah2 = new rojerusan.RSMaterialButtonRectangle();
        jLabel24 = new javax.swing.JLabel();
        pnHeader = new custom.PanelCustom();
        tPenjualan = new javax.swing.JLabel();
        panelViewPembelian = new javax.swing.JPanel();
        pnMain1 = new custom.PanelCustom();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblData1 = new javax.swing.JTable();
        iSearch1 = new javax.swing.JLabel();
        txtSearch1 = new custom.JTextFieldRounded();
        btnTambah3 = new rojerusan.RSMaterialButtonRectangle();
        btnTambah4 = new rojerusan.RSMaterialButtonRectangle();
        panelCustom3 = new custom.PanelCustom();
        panelCustom8 = new custom.PanelCustom();
        jLabel28 = new javax.swing.JLabel();
        panelCustom9 = new custom.PanelCustom();
        jLabel29 = new javax.swing.JLabel();
        panelCustom10 = new custom.PanelCustom();
        jLabel30 = new javax.swing.JLabel();
        panelCustom11 = new custom.PanelCustom();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtIdMember2 = new custom.JTextFieldRounded();
        txtIdMember3 = new custom.JTextFieldRounded();
        btnTambah5 = new rojerusan.RSMaterialButtonRectangle();
        jLabel33 = new javax.swing.JLabel();
        pnHeader1 = new custom.PanelCustom();
        tPenjualan1 = new javax.swing.JLabel();
        panelViewPresensi = new javax.swing.JPanel();
        pnMain2 = new custom.PanelCustom();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblData2 = new javax.swing.JTable();
        iSearch2 = new javax.swing.JLabel();
        txtSearch2 = new custom.JTextFieldRounded();
        btnTambah6 = new rojerusan.RSMaterialButtonRectangle();
        btnTambah7 = new rojerusan.RSMaterialButtonRectangle();
        panelCustom12 = new custom.PanelCustom();
        panelCustom13 = new custom.PanelCustom();
        jLabel34 = new javax.swing.JLabel();
        panelCustom14 = new custom.PanelCustom();
        jLabel35 = new javax.swing.JLabel();
        panelCustom15 = new custom.PanelCustom();
        jLabel36 = new javax.swing.JLabel();
        panelCustom16 = new custom.PanelCustom();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txtIdMember4 = new custom.JTextFieldRounded();
        txtIdMember5 = new custom.JTextFieldRounded();
        btnTambah8 = new rojerusan.RSMaterialButtonRectangle();
        jLabel39 = new javax.swing.JLabel();
        pnHeader2 = new custom.PanelCustom();
        tPenjualan2 = new javax.swing.JLabel();
        panelViewStok = new javax.swing.JPanel();
        pnMain3 = new custom.PanelCustom();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblData3 = new javax.swing.JTable();
        iSearch3 = new javax.swing.JLabel();
        txtSearch3 = new custom.JTextFieldRounded();
        btnTambah9 = new rojerusan.RSMaterialButtonRectangle();
        btnTambah10 = new rojerusan.RSMaterialButtonRectangle();
        panelCustom17 = new custom.PanelCustom();
        panelCustom18 = new custom.PanelCustom();
        jLabel40 = new javax.swing.JLabel();
        panelCustom19 = new custom.PanelCustom();
        jLabel41 = new javax.swing.JLabel();
        panelCustom20 = new custom.PanelCustom();
        jLabel42 = new javax.swing.JLabel();
        panelCustom21 = new custom.PanelCustom();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txtIdMember6 = new custom.JTextFieldRounded();
        txtIdMember7 = new custom.JTextFieldRounded();
        btnTambah11 = new rojerusan.RSMaterialButtonRectangle();
        jLabel45 = new javax.swing.JLabel();
        pnHeader3 = new custom.PanelCustom();
        tPenjualan3 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        panelMain.setLayout(new java.awt.CardLayout());

        panelViewPendapatan.setBackground(new java.awt.Color(248, 231, 246));
        panelViewPendapatan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnMain.setBackground(new java.awt.Color(255, 255, 255));
        pnMain.setRoundBottomLeft(20);
        pnMain.setRoundBottomRight(20);
        pnMain.setRoundTopLeft(20);
        pnMain.setRoundTopRight(20);
        pnMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblData.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Transaksi", "Tgl Transaksi", "Untung", "Petugas"
            }
        ));
        tblData.setGridColor(new java.awt.Color(255, 255, 255));
        tblData.setSelectionBackground(new java.awt.Color(75, 22, 76));
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        pnMain.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 1560, 690));

        iSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        pnMain.add(iSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 70, 30, 30));

        txtSearch.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        pnMain.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 60, 460, 50));

        btnTambah.setBackground(new java.awt.Color(75, 22, 76));
        btnTambah.setText("BATAL");
        btnTambah.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        pnMain.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 50, 140, 60));

        btnTambah1.setBackground(new java.awt.Color(75, 22, 76));
        btnTambah1.setText("TAMPILKAN");
        btnTambah1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        btnTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah1ActionPerformed(evt);
            }
        });
        pnMain.add(btnTambah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 150, 60));

        panelCustom2.setBackground(new java.awt.Color(221, 136, 207));
        panelCustom2.setRoundBottomLeft(50);
        panelCustom2.setRoundBottomRight(50);
        panelCustom2.setRoundTopLeft(50);
        panelCustom2.setRoundTopRight(50);
        panelCustom2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCustom4.setBackground(new java.awt.Color(221, 136, 207));
        panelCustom4.setRoundBottomLeft(50);
        panelCustom4.setRoundBottomRight(50);
        panelCustom4.setRoundTopLeft(50);
        panelCustom4.setRoundTopRight(50);
        panelCustom4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCustom4MouseClicked(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(75, 22, 76));
        jLabel23.setText("STOK PRODUCT");

        javax.swing.GroupLayout panelCustom4Layout = new javax.swing.GroupLayout(panelCustom4);
        panelCustom4.setLayout(panelCustom4Layout);
        panelCustom4Layout.setHorizontalGroup(
            panelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel23)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelCustom4Layout.setVerticalGroup(
            panelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel23)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelCustom2.add(panelCustom4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 210, 70));

        panelCustom5.setBackground(new java.awt.Color(221, 136, 207));
        panelCustom5.setRoundBottomLeft(50);
        panelCustom5.setRoundBottomRight(50);
        panelCustom5.setRoundTopLeft(50);
        panelCustom5.setRoundTopRight(50);
        panelCustom5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCustom5MouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(75, 22, 76));
        jLabel25.setText("PRESENSI");

        javax.swing.GroupLayout panelCustom5Layout = new javax.swing.GroupLayout(panelCustom5);
        panelCustom5.setLayout(panelCustom5Layout);
        panelCustom5Layout.setHorizontalGroup(
            panelCustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel25)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelCustom5Layout.setVerticalGroup(
            panelCustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel25)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelCustom2.add(panelCustom5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 190, 70));

        panelCustom6.setBackground(new java.awt.Color(75, 22, 76));
        panelCustom6.setRoundBottomLeft(50);
        panelCustom6.setRoundBottomRight(50);
        panelCustom6.setRoundTopLeft(50);
        panelCustom6.setRoundTopRight(50);
        panelCustom6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCustom6MouseClicked(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("PENDAPATAN");

        javax.swing.GroupLayout panelCustom6Layout = new javax.swing.GroupLayout(panelCustom6);
        panelCustom6.setLayout(panelCustom6Layout);
        panelCustom6Layout.setHorizontalGroup(
            panelCustom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom6Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(16, 16, 16))
        );
        panelCustom6Layout.setVerticalGroup(
            panelCustom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel26)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelCustom2.add(panelCustom6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 70));

        panelCustom7.setBackground(new java.awt.Color(221, 136, 207));
        panelCustom7.setRoundBottomLeft(50);
        panelCustom7.setRoundBottomRight(50);
        panelCustom7.setRoundTopLeft(50);
        panelCustom7.setRoundTopRight(50);
        panelCustom7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCustom7MouseClicked(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(75, 22, 76));
        jLabel27.setText("PEMBELIAN");

        javax.swing.GroupLayout panelCustom7Layout = new javax.swing.GroupLayout(panelCustom7);
        panelCustom7.setLayout(panelCustom7Layout);
        panelCustom7Layout.setHorizontalGroup(
            panelCustom7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom7Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(28, 28, 28))
        );
        panelCustom7Layout.setVerticalGroup(
            panelCustom7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel27)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelCustom2.add(panelCustom7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 190, 70));

        pnMain.add(panelCustom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 850, -1, 70));

        jLabel22.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel22.setText("Tanggal Mulai");
        pnMain.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtIdMember.setText("12/10/2025");
        txtIdMember.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txtIdMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMemberActionPerformed(evt);
            }
        });
        pnMain.add(txtIdMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 200, 50));

        txtIdMember1.setText("12/10/2025");
        txtIdMember1.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txtIdMember1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMember1ActionPerformed(evt);
            }
        });
        pnMain.add(txtIdMember1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 210, 50));

        btnTambah2.setBackground(new java.awt.Color(75, 22, 76));
        btnTambah2.setText("CETAK");
        btnTambah2.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        btnTambah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah2ActionPerformed(evt);
            }
        });
        pnMain.add(btnTambah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 140, 60));

        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel24.setText("Tanggal Sampai");
        pnMain.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        panelViewPendapatan.add(pnMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1600, 940));

        pnHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnHeader.setRoundBottomLeft(20);
        pnHeader.setRoundBottomRight(20);
        pnHeader.setRoundTopLeft(20);
        pnHeader.setRoundTopRight(20);
        pnHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tPenjualan.setBackground(new java.awt.Color(245, 245, 245));
        tPenjualan.setFont(new java.awt.Font("SansSerif", 1, 40)); // NOI18N
        tPenjualan.setForeground(new java.awt.Color(75, 22, 76));
        tPenjualan.setText("MENU LAPORAN");
        pnHeader.add(tPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        panelViewPendapatan.add(pnHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1600, 70));

        panelMain.add(panelViewPendapatan, "card2");

        panelViewPembelian.setBackground(new java.awt.Color(248, 231, 246));
        panelViewPembelian.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnMain1.setBackground(new java.awt.Color(255, 255, 255));
        pnMain1.setRoundBottomLeft(20);
        pnMain1.setRoundBottomRight(20);
        pnMain1.setRoundTopLeft(20);
        pnMain1.setRoundTopRight(20);
        pnMain1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblData1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tblData1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Transaksi", "Tgl Transaksi", "Total Pengeluaran", "Petugas"
            }
        ));
        tblData1.setGridColor(new java.awt.Color(255, 255, 255));
        tblData1.setSelectionBackground(new java.awt.Color(75, 22, 76));
        tblData1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblData1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblData1);

        pnMain1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 1560, 690));

        iSearch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        pnMain1.add(iSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 70, 30, 30));

        txtSearch1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        pnMain1.add(txtSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 60, 460, 50));

        btnTambah3.setBackground(new java.awt.Color(75, 22, 76));
        btnTambah3.setText("BATAL");
        btnTambah3.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        btnTambah3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah3ActionPerformed(evt);
            }
        });
        pnMain1.add(btnTambah3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 50, 140, 60));

        btnTambah4.setBackground(new java.awt.Color(75, 22, 76));
        btnTambah4.setText("TAMPILKAN");
        btnTambah4.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        btnTambah4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah4ActionPerformed(evt);
            }
        });
        pnMain1.add(btnTambah4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 150, 60));

        panelCustom3.setBackground(new java.awt.Color(221, 136, 207));
        panelCustom3.setRoundBottomLeft(50);
        panelCustom3.setRoundBottomRight(50);
        panelCustom3.setRoundTopLeft(50);
        panelCustom3.setRoundTopRight(50);
        panelCustom3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCustom8.setBackground(new java.awt.Color(221, 136, 207));
        panelCustom8.setRoundBottomLeft(50);
        panelCustom8.setRoundBottomRight(50);
        panelCustom8.setRoundTopLeft(50);
        panelCustom8.setRoundTopRight(50);
        panelCustom8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCustom8MouseClicked(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(75, 22, 76));
        jLabel28.setText("STOK PRODUCT");

        javax.swing.GroupLayout panelCustom8Layout = new javax.swing.GroupLayout(panelCustom8);
        panelCustom8.setLayout(panelCustom8Layout);
        panelCustom8Layout.setHorizontalGroup(
            panelCustom8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel28)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelCustom8Layout.setVerticalGroup(
            panelCustom8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel28)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelCustom3.add(panelCustom8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 210, 70));

        panelCustom9.setBackground(new java.awt.Color(221, 136, 207));
        panelCustom9.setRoundBottomLeft(50);
        panelCustom9.setRoundBottomRight(50);
        panelCustom9.setRoundTopLeft(50);
        panelCustom9.setRoundTopRight(50);
        panelCustom9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCustom9MouseClicked(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(75, 22, 76));
        jLabel29.setText("PRESENSI");

        javax.swing.GroupLayout panelCustom9Layout = new javax.swing.GroupLayout(panelCustom9);
        panelCustom9.setLayout(panelCustom9Layout);
        panelCustom9Layout.setHorizontalGroup(
            panelCustom9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom9Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel29)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelCustom9Layout.setVerticalGroup(
            panelCustom9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom9Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel29)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelCustom3.add(panelCustom9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 190, 70));

        panelCustom10.setBackground(new java.awt.Color(221, 136, 207));
        panelCustom10.setRoundBottomLeft(50);
        panelCustom10.setRoundBottomRight(50);
        panelCustom10.setRoundTopLeft(50);
        panelCustom10.setRoundTopRight(50);
        panelCustom10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCustom10MouseClicked(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(75, 22, 76));
        jLabel30.setText("PENDAPATAN");

        javax.swing.GroupLayout panelCustom10Layout = new javax.swing.GroupLayout(panelCustom10);
        panelCustom10.setLayout(panelCustom10Layout);
        panelCustom10Layout.setHorizontalGroup(
            panelCustom10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom10Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(16, 16, 16))
        );
        panelCustom10Layout.setVerticalGroup(
            panelCustom10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom10Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel30)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelCustom3.add(panelCustom10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 70));

        panelCustom11.setBackground(new java.awt.Color(75, 22, 76));
        panelCustom11.setRoundBottomLeft(50);
        panelCustom11.setRoundBottomRight(50);
        panelCustom11.setRoundTopLeft(50);
        panelCustom11.setRoundTopRight(50);
        panelCustom11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCustom11MouseClicked(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("PEMBELIAN");

        javax.swing.GroupLayout panelCustom11Layout = new javax.swing.GroupLayout(panelCustom11);
        panelCustom11.setLayout(panelCustom11Layout);
        panelCustom11Layout.setHorizontalGroup(
            panelCustom11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom11Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addGap(28, 28, 28))
        );
        panelCustom11Layout.setVerticalGroup(
            panelCustom11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom11Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel31)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelCustom3.add(panelCustom11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 190, 70));

        pnMain1.add(panelCustom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 850, -1, 70));

        jLabel32.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel32.setText("Tanggal Mulai");
        pnMain1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtIdMember2.setText("12/10/2025");
        txtIdMember2.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txtIdMember2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMember2ActionPerformed(evt);
            }
        });
        pnMain1.add(txtIdMember2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 200, 50));

        txtIdMember3.setText("12/10/2025");
        txtIdMember3.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txtIdMember3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMember3ActionPerformed(evt);
            }
        });
        pnMain1.add(txtIdMember3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 210, 50));

        btnTambah5.setBackground(new java.awt.Color(75, 22, 76));
        btnTambah5.setText("CETAK");
        btnTambah5.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        btnTambah5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah5ActionPerformed(evt);
            }
        });
        pnMain1.add(btnTambah5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 140, 60));

        jLabel33.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel33.setText("Tanggal Sampai");
        pnMain1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        panelViewPembelian.add(pnMain1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1600, 940));

        pnHeader1.setBackground(new java.awt.Color(255, 255, 255));
        pnHeader1.setRoundBottomLeft(20);
        pnHeader1.setRoundBottomRight(20);
        pnHeader1.setRoundTopLeft(20);
        pnHeader1.setRoundTopRight(20);
        pnHeader1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tPenjualan1.setBackground(new java.awt.Color(245, 245, 245));
        tPenjualan1.setFont(new java.awt.Font("SansSerif", 1, 40)); // NOI18N
        tPenjualan1.setForeground(new java.awt.Color(75, 22, 76));
        tPenjualan1.setText("MENU LAPORAN");
        pnHeader1.add(tPenjualan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        panelViewPembelian.add(pnHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1600, 70));

        panelMain.add(panelViewPembelian, "card2");

        panelViewPresensi.setBackground(new java.awt.Color(248, 231, 246));
        panelViewPresensi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnMain2.setBackground(new java.awt.Color(255, 255, 255));
        pnMain2.setRoundBottomLeft(20);
        pnMain2.setRoundBottomRight(20);
        pnMain2.setRoundTopLeft(20);
        pnMain2.setRoundTopRight(20);
        pnMain2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblData2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tblData2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama Karyawan", "Tanggal", "Jam Login", "Jam Logout", "Keterangan"
            }
        ));
        tblData2.setGridColor(new java.awt.Color(255, 255, 255));
        tblData2.setSelectionBackground(new java.awt.Color(75, 22, 76));
        tblData2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblData2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblData2);

        pnMain2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 1560, 690));

        iSearch2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        pnMain2.add(iSearch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 70, 30, 30));

        txtSearch2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        pnMain2.add(txtSearch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 60, 460, 50));

        btnTambah6.setBackground(new java.awt.Color(75, 22, 76));
        btnTambah6.setText("BATAL");
        btnTambah6.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        btnTambah6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah6ActionPerformed(evt);
            }
        });
        pnMain2.add(btnTambah6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 50, 140, 60));

        btnTambah7.setBackground(new java.awt.Color(75, 22, 76));
        btnTambah7.setText("TAMPILKAN");
        btnTambah7.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        btnTambah7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah7ActionPerformed(evt);
            }
        });
        pnMain2.add(btnTambah7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 150, 60));

        panelCustom12.setBackground(new java.awt.Color(221, 136, 207));
        panelCustom12.setRoundBottomLeft(50);
        panelCustom12.setRoundBottomRight(50);
        panelCustom12.setRoundTopLeft(50);
        panelCustom12.setRoundTopRight(50);
        panelCustom12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCustom13.setBackground(new java.awt.Color(221, 136, 207));
        panelCustom13.setRoundBottomLeft(50);
        panelCustom13.setRoundBottomRight(50);
        panelCustom13.setRoundTopLeft(50);
        panelCustom13.setRoundTopRight(50);
        panelCustom13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCustom13MouseClicked(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(75, 22, 76));
        jLabel34.setText("STOK PRODUCT");

        javax.swing.GroupLayout panelCustom13Layout = new javax.swing.GroupLayout(panelCustom13);
        panelCustom13.setLayout(panelCustom13Layout);
        panelCustom13Layout.setHorizontalGroup(
            panelCustom13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom13Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel34)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelCustom13Layout.setVerticalGroup(
            panelCustom13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom13Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel34)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelCustom12.add(panelCustom13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 210, 70));

        panelCustom14.setBackground(new java.awt.Color(75, 22, 76));
        panelCustom14.setRoundBottomLeft(50);
        panelCustom14.setRoundBottomRight(50);
        panelCustom14.setRoundTopLeft(50);
        panelCustom14.setRoundTopRight(50);
        panelCustom14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCustom14MouseClicked(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("PRESENSI");

        javax.swing.GroupLayout panelCustom14Layout = new javax.swing.GroupLayout(panelCustom14);
        panelCustom14.setLayout(panelCustom14Layout);
        panelCustom14Layout.setHorizontalGroup(
            panelCustom14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom14Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel35)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelCustom14Layout.setVerticalGroup(
            panelCustom14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom14Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel35)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelCustom12.add(panelCustom14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 190, 70));

        panelCustom15.setBackground(new java.awt.Color(221, 136, 207));
        panelCustom15.setRoundBottomLeft(50);
        panelCustom15.setRoundBottomRight(50);
        panelCustom15.setRoundTopLeft(50);
        panelCustom15.setRoundTopRight(50);
        panelCustom15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCustom15MouseClicked(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(75, 22, 76));
        jLabel36.setText("PENDAPATAN");

        javax.swing.GroupLayout panelCustom15Layout = new javax.swing.GroupLayout(panelCustom15);
        panelCustom15.setLayout(panelCustom15Layout);
        panelCustom15Layout.setHorizontalGroup(
            panelCustom15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom15Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel36)
                .addGap(16, 16, 16))
        );
        panelCustom15Layout.setVerticalGroup(
            panelCustom15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom15Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel36)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelCustom12.add(panelCustom15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 70));

        panelCustom16.setBackground(new java.awt.Color(221, 136, 207));
        panelCustom16.setRoundBottomLeft(50);
        panelCustom16.setRoundBottomRight(50);
        panelCustom16.setRoundTopLeft(50);
        panelCustom16.setRoundTopRight(50);
        panelCustom16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCustom16MouseClicked(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(75, 22, 76));
        jLabel37.setText("PEMBELIAN");

        javax.swing.GroupLayout panelCustom16Layout = new javax.swing.GroupLayout(panelCustom16);
        panelCustom16.setLayout(panelCustom16Layout);
        panelCustom16Layout.setHorizontalGroup(
            panelCustom16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom16Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel37)
                .addGap(28, 28, 28))
        );
        panelCustom16Layout.setVerticalGroup(
            panelCustom16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom16Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel37)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelCustom12.add(panelCustom16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 190, 70));

        pnMain2.add(panelCustom12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 850, -1, 70));

        jLabel38.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel38.setText("Tanggal Mulai");
        pnMain2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtIdMember4.setText("12/10/2025");
        txtIdMember4.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txtIdMember4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMember4ActionPerformed(evt);
            }
        });
        pnMain2.add(txtIdMember4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 200, 50));

        txtIdMember5.setText("12/10/2025");
        txtIdMember5.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txtIdMember5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMember5ActionPerformed(evt);
            }
        });
        pnMain2.add(txtIdMember5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 210, 50));

        btnTambah8.setBackground(new java.awt.Color(75, 22, 76));
        btnTambah8.setText("CETAK");
        btnTambah8.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        btnTambah8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah8ActionPerformed(evt);
            }
        });
        pnMain2.add(btnTambah8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 140, 60));

        jLabel39.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel39.setText("Tanggal Sampai");
        pnMain2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        panelViewPresensi.add(pnMain2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1600, 940));

        pnHeader2.setBackground(new java.awt.Color(255, 255, 255));
        pnHeader2.setRoundBottomLeft(20);
        pnHeader2.setRoundBottomRight(20);
        pnHeader2.setRoundTopLeft(20);
        pnHeader2.setRoundTopRight(20);
        pnHeader2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tPenjualan2.setBackground(new java.awt.Color(245, 245, 245));
        tPenjualan2.setFont(new java.awt.Font("SansSerif", 1, 40)); // NOI18N
        tPenjualan2.setForeground(new java.awt.Color(75, 22, 76));
        tPenjualan2.setText("MENU LAPORAN");
        pnHeader2.add(tPenjualan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        panelViewPresensi.add(pnHeader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1600, 70));

        panelMain.add(panelViewPresensi, "card2");

        panelViewStok.setBackground(new java.awt.Color(248, 231, 246));
        panelViewStok.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnMain3.setBackground(new java.awt.Color(255, 255, 255));
        pnMain3.setRoundBottomLeft(20);
        pnMain3.setRoundBottomRight(20);
        pnMain3.setRoundTopLeft(20);
        pnMain3.setRoundTopRight(20);
        pnMain3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblData3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tblData3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kategori", "Nama Product", "Tgl Expired", "Harga Beli", "Harga Jual", "Jumlah Stok"
            }
        ));
        tblData3.setGridColor(new java.awt.Color(255, 255, 255));
        tblData3.setSelectionBackground(new java.awt.Color(75, 22, 76));
        tblData3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblData3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblData3);

        pnMain3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 1560, 690));

        iSearch3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        pnMain3.add(iSearch3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 70, 30, 30));

        txtSearch3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        pnMain3.add(txtSearch3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 60, 460, 50));

        btnTambah9.setBackground(new java.awt.Color(75, 22, 76));
        btnTambah9.setText("BATAL");
        btnTambah9.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        btnTambah9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah9ActionPerformed(evt);
            }
        });
        pnMain3.add(btnTambah9, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 50, 140, 60));

        btnTambah10.setBackground(new java.awt.Color(75, 22, 76));
        btnTambah10.setText("TAMPILKAN");
        btnTambah10.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        btnTambah10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah10ActionPerformed(evt);
            }
        });
        pnMain3.add(btnTambah10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 150, 60));

        panelCustom17.setBackground(new java.awt.Color(221, 136, 207));
        panelCustom17.setRoundBottomLeft(50);
        panelCustom17.setRoundBottomRight(50);
        panelCustom17.setRoundTopLeft(50);
        panelCustom17.setRoundTopRight(50);
        panelCustom17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCustom18.setBackground(new java.awt.Color(75, 22, 76));
        panelCustom18.setRoundBottomLeft(50);
        panelCustom18.setRoundBottomRight(50);
        panelCustom18.setRoundTopLeft(50);
        panelCustom18.setRoundTopRight(50);
        panelCustom18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCustom18MouseClicked(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("STOK PRODUCT");

        javax.swing.GroupLayout panelCustom18Layout = new javax.swing.GroupLayout(panelCustom18);
        panelCustom18.setLayout(panelCustom18Layout);
        panelCustom18Layout.setHorizontalGroup(
            panelCustom18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom18Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel40)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelCustom18Layout.setVerticalGroup(
            panelCustom18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom18Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel40)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelCustom17.add(panelCustom18, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 210, 70));

        panelCustom19.setBackground(new java.awt.Color(221, 136, 207));
        panelCustom19.setRoundBottomLeft(50);
        panelCustom19.setRoundBottomRight(50);
        panelCustom19.setRoundTopLeft(50);
        panelCustom19.setRoundTopRight(50);
        panelCustom19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCustom19MouseClicked(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(75, 22, 76));
        jLabel41.setText("PRESENSI");

        javax.swing.GroupLayout panelCustom19Layout = new javax.swing.GroupLayout(panelCustom19);
        panelCustom19.setLayout(panelCustom19Layout);
        panelCustom19Layout.setHorizontalGroup(
            panelCustom19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom19Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel41)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelCustom19Layout.setVerticalGroup(
            panelCustom19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom19Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel41)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelCustom17.add(panelCustom19, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 190, 70));

        panelCustom20.setBackground(new java.awt.Color(221, 136, 207));
        panelCustom20.setRoundBottomLeft(50);
        panelCustom20.setRoundBottomRight(50);
        panelCustom20.setRoundTopLeft(50);
        panelCustom20.setRoundTopRight(50);
        panelCustom20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCustom20MouseClicked(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(75, 22, 76));
        jLabel42.setText("PENDAPATAN");

        javax.swing.GroupLayout panelCustom20Layout = new javax.swing.GroupLayout(panelCustom20);
        panelCustom20.setLayout(panelCustom20Layout);
        panelCustom20Layout.setHorizontalGroup(
            panelCustom20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom20Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel42)
                .addGap(16, 16, 16))
        );
        panelCustom20Layout.setVerticalGroup(
            panelCustom20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom20Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel42)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelCustom17.add(panelCustom20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 70));

        panelCustom21.setBackground(new java.awt.Color(221, 136, 207));
        panelCustom21.setRoundBottomLeft(50);
        panelCustom21.setRoundBottomRight(50);
        panelCustom21.setRoundTopLeft(50);
        panelCustom21.setRoundTopRight(50);
        panelCustom21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCustom21MouseClicked(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(75, 22, 76));
        jLabel43.setText("PEMBELIAN");

        javax.swing.GroupLayout panelCustom21Layout = new javax.swing.GroupLayout(panelCustom21);
        panelCustom21.setLayout(panelCustom21Layout);
        panelCustom21Layout.setHorizontalGroup(
            panelCustom21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom21Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel43)
                .addGap(28, 28, 28))
        );
        panelCustom21Layout.setVerticalGroup(
            panelCustom21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom21Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel43)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelCustom17.add(panelCustom21, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 190, 70));

        pnMain3.add(panelCustom17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 850, -1, 70));

        jLabel44.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel44.setText("Tanggal Mulai");
        pnMain3.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtIdMember6.setText("12/10/2025");
        txtIdMember6.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txtIdMember6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMember6ActionPerformed(evt);
            }
        });
        pnMain3.add(txtIdMember6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 200, 50));

        txtIdMember7.setText("12/10/2025");
        txtIdMember7.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txtIdMember7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMember7ActionPerformed(evt);
            }
        });
        pnMain3.add(txtIdMember7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 210, 50));

        btnTambah11.setBackground(new java.awt.Color(75, 22, 76));
        btnTambah11.setText("CETAK");
        btnTambah11.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        btnTambah11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah11ActionPerformed(evt);
            }
        });
        pnMain3.add(btnTambah11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 140, 60));

        jLabel45.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel45.setText("Tanggal Sampai");
        pnMain3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        panelViewStok.add(pnMain3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1600, 940));

        pnHeader3.setBackground(new java.awt.Color(255, 255, 255));
        pnHeader3.setRoundBottomLeft(20);
        pnHeader3.setRoundBottomRight(20);
        pnHeader3.setRoundTopLeft(20);
        pnHeader3.setRoundTopRight(20);
        pnHeader3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tPenjualan3.setBackground(new java.awt.Color(245, 245, 245));
        tPenjualan3.setFont(new java.awt.Font("SansSerif", 1, 40)); // NOI18N
        tPenjualan3.setForeground(new java.awt.Color(75, 22, 76));
        tPenjualan3.setText("MENU LAPORAN");
        pnHeader3.add(tPenjualan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        panelViewStok.add(pnHeader3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1600, 70));

        panelMain.add(panelViewStok, "card2");

        add(panelMain, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked

    }//GEN-LAST:event_tblDataMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah1ActionPerformed

    }//GEN-LAST:event_btnTambah1ActionPerformed

    private void txtIdMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMemberActionPerformed

    private void txtIdMember1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMember1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMember1ActionPerformed

    private void btnTambah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambah2ActionPerformed

    private void tblData1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblData1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblData1MouseClicked

    private void btnTambah3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambah3ActionPerformed

    private void btnTambah4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambah4ActionPerformed

    private void txtIdMember2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMember2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMember2ActionPerformed

    private void txtIdMember3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMember3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMember3ActionPerformed

    private void btnTambah5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambah5ActionPerformed

    private void tblData2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblData2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblData2MouseClicked

    private void btnTambah6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambah6ActionPerformed

    private void btnTambah7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambah7ActionPerformed

    private void txtIdMember4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMember4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMember4ActionPerformed

    private void txtIdMember5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMember5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMember5ActionPerformed

    private void btnTambah8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambah8ActionPerformed

    private void tblData3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblData3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblData3MouseClicked

    private void btnTambah9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambah9ActionPerformed

    private void btnTambah10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambah10ActionPerformed

    private void txtIdMember6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMember6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMember6ActionPerformed

    private void txtIdMember7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMember7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMember7ActionPerformed

    private void btnTambah11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambah11ActionPerformed

    private void panelCustom6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCustom6MouseClicked
        panelViewPendapatan();
    }//GEN-LAST:event_panelCustom6MouseClicked

    private void panelCustom7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCustom7MouseClicked
        panelViewPembelian();
    }//GEN-LAST:event_panelCustom7MouseClicked

    private void panelCustom5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCustom5MouseClicked
        panelViewPresensi();
    }//GEN-LAST:event_panelCustom5MouseClicked

    private void panelCustom4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCustom4MouseClicked
        panelViewStok();
    }//GEN-LAST:event_panelCustom4MouseClicked

    private void panelCustom10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCustom10MouseClicked
        panelViewPendapatan();
    }//GEN-LAST:event_panelCustom10MouseClicked

    private void panelCustom11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCustom11MouseClicked
        panelViewPembelian();
    }//GEN-LAST:event_panelCustom11MouseClicked

    private void panelCustom9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCustom9MouseClicked
        panelViewPresensi();
    }//GEN-LAST:event_panelCustom9MouseClicked

    private void panelCustom8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCustom8MouseClicked
        panelViewStok();
    }//GEN-LAST:event_panelCustom8MouseClicked

    private void panelCustom15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCustom15MouseClicked
        panelViewPendapatan();
    }//GEN-LAST:event_panelCustom15MouseClicked

    private void panelCustom16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCustom16MouseClicked
        panelViewPembelian();
    }//GEN-LAST:event_panelCustom16MouseClicked

    private void panelCustom14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCustom14MouseClicked
        panelViewPresensi();
    }//GEN-LAST:event_panelCustom14MouseClicked

    private void panelCustom13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCustom13MouseClicked
        panelViewStok();
    }//GEN-LAST:event_panelCustom13MouseClicked

    private void panelCustom20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCustom20MouseClicked
        panelViewPendapatan();
    }//GEN-LAST:event_panelCustom20MouseClicked

    private void panelCustom21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCustom21MouseClicked
        panelViewPembelian();
    }//GEN-LAST:event_panelCustom21MouseClicked

    private void panelCustom19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCustom19MouseClicked
        panelViewPresensi();
    }//GEN-LAST:event_panelCustom19MouseClicked

    private void panelCustom18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCustom18MouseClicked
        panelViewStok();
    }//GEN-LAST:event_panelCustom18MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btnTambah;
    private rojerusan.RSMaterialButtonRectangle btnTambah1;
    private rojerusan.RSMaterialButtonRectangle btnTambah10;
    private rojerusan.RSMaterialButtonRectangle btnTambah11;
    private rojerusan.RSMaterialButtonRectangle btnTambah2;
    private rojerusan.RSMaterialButtonRectangle btnTambah3;
    private rojerusan.RSMaterialButtonRectangle btnTambah4;
    private rojerusan.RSMaterialButtonRectangle btnTambah5;
    private rojerusan.RSMaterialButtonRectangle btnTambah6;
    private rojerusan.RSMaterialButtonRectangle btnTambah7;
    private rojerusan.RSMaterialButtonRectangle btnTambah8;
    private rojerusan.RSMaterialButtonRectangle btnTambah9;
    private javax.swing.JLabel iSearch;
    private javax.swing.JLabel iSearch1;
    private javax.swing.JLabel iSearch2;
    private javax.swing.JLabel iSearch3;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private custom.PanelCustom panelCustom10;
    private custom.PanelCustom panelCustom11;
    private custom.PanelCustom panelCustom12;
    private custom.PanelCustom panelCustom13;
    private custom.PanelCustom panelCustom14;
    private custom.PanelCustom panelCustom15;
    private custom.PanelCustom panelCustom16;
    private custom.PanelCustom panelCustom17;
    private custom.PanelCustom panelCustom18;
    private custom.PanelCustom panelCustom19;
    private custom.PanelCustom panelCustom2;
    private custom.PanelCustom panelCustom20;
    private custom.PanelCustom panelCustom21;
    private custom.PanelCustom panelCustom3;
    private custom.PanelCustom panelCustom4;
    private custom.PanelCustom panelCustom5;
    private custom.PanelCustom panelCustom6;
    private custom.PanelCustom panelCustom7;
    private custom.PanelCustom panelCustom8;
    private custom.PanelCustom panelCustom9;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelViewPembelian;
    private javax.swing.JPanel panelViewPendapatan;
    private javax.swing.JPanel panelViewPresensi;
    private javax.swing.JPanel panelViewStok;
    private custom.PanelCustom pnHeader;
    private custom.PanelCustom pnHeader1;
    private custom.PanelCustom pnHeader2;
    private custom.PanelCustom pnHeader3;
    private custom.PanelCustom pnMain;
    private custom.PanelCustom pnMain1;
    private custom.PanelCustom pnMain2;
    private custom.PanelCustom pnMain3;
    private javax.swing.JLabel tPenjualan;
    private javax.swing.JLabel tPenjualan1;
    private javax.swing.JLabel tPenjualan2;
    private javax.swing.JLabel tPenjualan3;
    private javax.swing.JTable tblData;
    private javax.swing.JTable tblData1;
    private javax.swing.JTable tblData2;
    private javax.swing.JTable tblData3;
    private custom.JTextFieldRounded txtIdMember;
    private custom.JTextFieldRounded txtIdMember1;
    private custom.JTextFieldRounded txtIdMember2;
    private custom.JTextFieldRounded txtIdMember3;
    private custom.JTextFieldRounded txtIdMember4;
    private custom.JTextFieldRounded txtIdMember5;
    private custom.JTextFieldRounded txtIdMember6;
    private custom.JTextFieldRounded txtIdMember7;
    private custom.JTextFieldRounded txtSearch;
    private custom.JTextFieldRounded txtSearch1;
    private custom.JTextFieldRounded txtSearch2;
    private custom.JTextFieldRounded txtSearch3;
    // End of variables declaration//GEN-END:variables
    
    
    private void panelViewPendapatan() {
        panelMain.removeAll();
        panelMain.add(panelViewPendapatan);
        panelMain.repaint();
        panelMain.revalidate();
    }
    
    private void panelViewPembelian() {
        panelMain.removeAll();
        panelMain.add(panelViewPembelian);
        panelMain.repaint();
        panelMain.revalidate();
    }
    
    private void panelViewPresensi() {
        panelMain.removeAll();
        panelMain.add(panelViewPresensi);
        panelMain.repaint();
        panelMain.revalidate();
    }
    
    private void panelViewStok() {
        panelMain.removeAll();
        panelMain.add(panelViewStok);
        panelMain.repaint();
        panelMain.revalidate();
    }
    
    private void fieldColor(JTextField field) {
        field.setOpaque(true);
        field.setEditable(false);
        field.setBackground(new Color(219, 219, 219));
    }
    
    private void calculateTotalPages(){
    int totalData = getTotalData(); // Ambil total data dari tabel
    totalPages = (int) Math.ceil((double) totalData / dataPerHalaman);
    }
    
    private int getTotalData(){
        int totalData = 0;
        
        try {
            String sql = "SELECT COUNT(*) AS total FROM transaksi_penjualan";
            try (PreparedStatement st = conn.prepareStatement(sql)){
                ResultSet rs = st.executeQuery();
                if(rs.next()){
                    totalData = rs.getInt("total");
                }
            } 
        }catch (Exception e) {     
            Logger.getLogger(menuLaporan.class.getName()).log(Level.SEVERE,null, e);
        }
        return totalData;
    }
    
    public void getData(int startIndex, int entriesPage, DefaultTableModel model) {
        model.setRowCount(0);
        
        try {
           String sql = "SELECT t.id_transaksi, cu.nama_member, DATE(t.tgl_penjualan) AS tgl_penjualan, t.total_harga, t.jumlah_bayar, "
                   + "t.kembalian, us.nama AS nama_user FROM transaksi_penjualan t INNER JOIN member cu ON t.id_member = cu.id_member "
                   + "INNER JOIN user us ON t.id_user = us.id_user ORDER BY t.id_transaksi ASC LIMIT ?,?";
           try (PreparedStatement st = conn.prepareStatement(sql)) {
               st.setInt(1, startIndex);
               st.setInt(2, entriesPage);
               ResultSet rs = st.executeQuery();
               
               while (rs.next()) {
                    String idTransaksi = rs.getString("id_transaksi");
                    String namaMember = rs.getString("nama_member");
                    String tglPenjualan = rs.getString("tgl_penjualan");
                    int totalHarga = rs.getInt("total_harga");
                    int jumlahBayar = rs.getInt("jumlah_bayar");
                    int Kembalian = rs.getInt("kembalian");
                    String namaUser = rs.getString("nama_user");
                    

                    Object[] rowData = {idTransaksi, namaMember, tglPenjualan, 
                        totalHarga, jumlahBayar, Kembalian, namaUser};
                    model.addRow(rowData);
                }
           }
        }catch (Exception e) {
            Logger.getLogger(menuLaporan.class.getName()).log(Level.SEVERE,null, e);
        }
    }
    
    
    private void loadData() {
        calculateTotalPages();
        int totalData = getTotalData();

        int startIndex = (halamanSaatIni - 1) * dataPerHalaman; // Indeks awal untuk pagination
        getData(startIndex, dataPerHalaman, (DefaultTableModel) tblData.getModel());
    }
    
    private void setTabelModel() {
        DefaultTableModel model = (DefaultTableModel) tblData.getModel();
    }

}
