package bareSkinMenu;

import menu.*;
import config.koneksi;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author user
 */
public class tambahProduct extends javax.swing.JDialog {
    
    private int halamanSaatIni = 1;
    private int dataPerHalaman = 14;
    private int totalPages;
    private Connection conn;
    
    private String id_product;
    private String nama_product;
    private String stok_product;
    private String satuan;
    private String harga;
    
    public String getId_product() {
        return id_product;
    }

    public String getNama_product() {
        return nama_product;
    }

    public String getStok_product() {
        return stok_product;
    }

    public String getSatuan() {
        return satuan;
    }
    
    public String getHarga() {
        return harga;
    }

    public tambahProduct(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        conn = koneksi.getConnection();
        finishing();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelView = new javax.swing.JPanel();
        databahan = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtIdProduct = new custom.JTextFieldRounded();
        jLabel23 = new javax.swing.JLabel();
        txtNamaProduct = new custom.JTextFieldRounded();
        jLabel25 = new javax.swing.JLabel();
        txtStok = new custom.JTextFieldRounded();
        jLabel28 = new javax.swing.JLabel();
        cbxSatuan = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        txtTanggalExpired = new custom.JTextFieldRounded();
        jLabel32 = new javax.swing.JLabel();
        cbxKategori = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        txtHargaBeli = new custom.JTextFieldRounded();
        jLabel26 = new javax.swing.JLabel();
        txtHargaJual = new custom.JTextFieldRounded();
        btnSimpan = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelView.setBackground(new java.awt.Color(255, 255, 255));
        panelView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        databahan.setBackground(new java.awt.Color(75, 22, 76));
        databahan.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        databahan.setForeground(new java.awt.Color(75, 22, 76));
        databahan.setText("TAMBAH PRODUCT");
        panelView.add(databahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jLabel22.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel22.setText("ID Product");
        panelView.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        txtIdProduct.setText("9999999999999");
        txtIdProduct.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txtIdProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProductActionPerformed(evt);
            }
        });
        panelView.add(txtIdProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 190, 50));

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel23.setText("Nama Product");
        panelView.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        txtNamaProduct.setText("Scarlett Whitening Brightly ");
        txtNamaProduct.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        panelView.add(txtNamaProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 430, 50));

        jLabel25.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel25.setText("Stok");
        panelView.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, -1, -1));

        txtStok.setText("100");
        txtStok.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        panelView.add(txtStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 60, 50));

        jLabel28.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel28.setText("Satuan");
        panelView.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, -1));

        cbxSatuan.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        cbxSatuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Satuan Product", "Item", "Gram", "KiloGram", "Renteng", "Slop Kecil", "Slop Besar", "Pak", "Roll", "Kotak Susu" }));
        cbxSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSatuanActionPerformed(evt);
            }
        });
        panelView.add(cbxSatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 360, 50));

        jLabel31.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel31.setText("Tanggal Expired");
        panelView.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, -1));

        txtTanggalExpired.setText("1");
        txtTanggalExpired.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        panelView.add(txtTanggalExpired, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 170, -1));

        jLabel32.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel32.setText("Kategori");
        panelView.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        cbxKategori.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        cbxKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kategori Product", "Item", "Gram", "KiloGram", "Renteng", "Slop Kecil", "Slop Besar", "Pak", "Roll", "Kotak Susu" }));
        cbxKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxKategoriActionPerformed(evt);
            }
        });
        panelView.add(cbxKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 430, 50));

        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel24.setText("Harga Beli");
        panelView.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, -1));

        txtHargaBeli.setText("10.000.000");
        txtHargaBeli.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        panelView.add(txtHargaBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 140, -1));

        jLabel26.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel26.setText("Harga Jual");
        panelView.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, -1, -1));

        txtHargaJual.setText("10.000.000");
        txtHargaJual.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        panelView.add(txtHargaJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, 140, -1));

        btnSimpan.setBackground(new java.awt.Color(75, 22, 76));
        btnSimpan.setText("SIMPAN");
        btnSimpan.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        panelView.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 170, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelView, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelView, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void cbxKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxKategoriActionPerformed

    private void cbxSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSatuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSatuanActionPerformed

    private void txtIdProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                tambahProduct dialog = new tambahProduct(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btnSimpan;
    private javax.swing.JComboBox<String> cbxKategori;
    private javax.swing.JComboBox<String> cbxSatuan;
    private javax.swing.JLabel databahan;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel panelView;
    private custom.JTextFieldRounded txtHargaBeli;
    private custom.JTextFieldRounded txtHargaJual;
    private custom.JTextFieldRounded txtIdProduct;
    private custom.JTextFieldRounded txtNamaProduct;
    private custom.JTextFieldRounded txtStok;
    private custom.JTextFieldRounded txtTanggalExpired;
    // End of variables declaration//GEN-END:variables

    private void fieldColor(JTextField field) {
        field.setOpaque(true);
        field.setEditable(false);
        field.setBackground(new Color(219, 219, 219));
    }

    private void finishing() {
        fieldColor(txtStok);
        fieldColor(txtHargaBeli);
        fieldColor(txtHargaJual);
    }
    
    
    private void calculateTotalPages(){
        int totalData = getTotalData();
        totalPages = (int) Math.ceil((double) totalData / dataPerHalaman );
    }
    
    private int getTotalData(){
        int totalData = 0;
        
        try {
            String sql = "SELECT COUNT(*) AS total FROM product";
            try (PreparedStatement st = conn.prepareStatement(sql)){
                ResultSet rs = st.executeQuery();
                if(rs.next()){
                    totalData = rs.getInt("total");
                }
            } 
        }catch (Exception e) {     
            Logger.getLogger(tambahProduct.class.getName()).log(Level.SEVERE,null, e);
        }
        
        return totalData;
    }
    
    
    public void getData(int startIndex, int entriesPage, DefaultTableModel model) {
        model.setRowCount(0);
        
        try {
           String sql = "SELECT * FROM product LIMIT ?,?";
           try (PreparedStatement st = conn.prepareStatement(sql)) {
               st.setInt(1, startIndex);
               st.setInt(2, entriesPage);
               ResultSet rs = st.executeQuery();
               
               while (rs.next()) {
                    String idProduct = rs.getString("id_product");
                    String namaProduct = rs.getString("nama_product");
                    int stokProduct = rs.getInt("stok_product");
                    String satuan = rs.getString("satuan");
                    int hargaBeli = rs.getInt("harga_beli");
                    int hargaJual = rs.getInt("harga_jual");
                    String numberProduct = rs.getString("number_product");
                    String tglExpired = rs.getString("tgl_expired");

                    Object[] rowData = {idProduct, namaProduct, stokProduct, satuan, hargaBeli, hargaJual, numberProduct, tglExpired};
                    model.addRow(rowData);
                }
           }
        }catch (Exception e) {
            Logger.getLogger(tambahProduct.class.getName()).log(Level.SEVERE,null, e);
        }
    }
    
    
    

    
}
