package bareSkinMenu;

import config.koneksi;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author user
 */
public class tambahSupplier extends javax.swing.JDialog {
    
    private int halamanSaatIni = 1;
    private int dataPerHalaman = 14;
    private int totalPages;
    private Connection conn;
    
    private String id_supplier;
    private String nama_supplier;
    private String alamat;
    private String no_telepon;
    
    public String getId_supplier() {
        return id_supplier;
    }

    public String getNama_supplier() {
        return nama_supplier;
    }

    public String getAlamat() {
        return alamat;
    }

    public String getNo_telepon() {
        return no_telepon;
    }


    public tambahSupplier(java.awt.Frame parent, boolean modal, 
            String id, String nama, String nomor, String alamat) {
    super(parent, modal);
    initComponents();
    setLocationRelativeTo(null);

    conn = koneksi.getConnection();

    // Set data ke field dan komponen input
    this.id_supplier = id;
    this.nama_supplier = nama;
    this.no_telepon = nomor;
    this.alamat = alamat;

    txtIdSupplier.setText(id);
    txtNamaSupplier.setText(nama);
    txtNomorTelepon.setText(nomor);
    txtAlamat.setText(alamat);
    btnSimpan.setText("SIMPAN");
    
    if (!txtIdSupplier.getText().trim().isEmpty()) {
        btnSimpan.setText("UBAH");
        txtIdSupplier.setEnabled(false);
        fieldColor(txtIdSupplier);
    } 
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelView = new javax.swing.JPanel();
        databahan = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtIdSupplier = new custom.JTextFieldRounded();
        jLabel23 = new javax.swing.JLabel();
        txtAlamat = new custom.JTextFieldRounded();
        txtNamaSupplier = new custom.JTextFieldRounded();
        jLabel31 = new javax.swing.JLabel();
        txtNomorTelepon = new custom.JTextFieldRounded();
        jLabel32 = new javax.swing.JLabel();
        btnSimpan = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelView.setBackground(new java.awt.Color(255, 255, 255));
        panelView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        databahan.setBackground(new java.awt.Color(75, 22, 76));
        databahan.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        databahan.setForeground(new java.awt.Color(75, 22, 76));
        databahan.setText("TAMBAH SUPPLIER");
        panelView.add(databahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jLabel22.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel22.setText("ID Supplier");
        panelView.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        txtIdSupplier.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txtIdSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdSupplierActionPerformed(evt);
            }
        });
        panelView.add(txtIdSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 190, 50));

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel23.setText("Nama Supplier");
        panelView.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        txtAlamat.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        panelView.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 430, 50));

        txtNamaSupplier.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        panelView.add(txtNamaSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 430, 50));

        jLabel31.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel31.setText("Nomor Telepon");
        panelView.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, -1));

        txtNomorTelepon.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        panelView.add(txtNomorTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 180, -1));

        jLabel32.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel32.setText("Alamat");
        panelView.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, -1, -1));

        btnSimpan.setBackground(new java.awt.Color(75, 22, 76));
        btnSimpan.setText("SIMPAN");
        btnSimpan.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        panelView.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 170, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelView, javax.swing.GroupLayout.DEFAULT_SIZE, 1021, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelView, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if(btnSimpan.getText().equals("SIMPAN"))
            {
                insertData();
            }
        else if(btnSimpan.getText().equals("UBAH"))
            {
                updateData();
            }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtIdSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdSupplierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btnSimpan;
    private javax.swing.JLabel databahan;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel panelView;
    private custom.JTextFieldRounded txtAlamat;
    private custom.JTextFieldRounded txtIdSupplier;
    private custom.JTextFieldRounded txtNamaSupplier;
    private custom.JTextFieldRounded txtNomorTelepon;
    // End of variables declaration//GEN-END:variables

    private void fieldColor(JTextField field) {
        field.setOpaque(true);
        field.setEditable(false);
        field.setBackground(new Color(219, 219, 219));
    }

    
    private void resetForm() {
        txtIdSupplier.setText("");
        txtNamaSupplier.setText("");
        txtAlamat.setText("");
        txtNomorTelepon.setText("");
    }
    
    private void insertData() {
        String id_member = txtIdSupplier.getText().trim();
        String nama_member = txtNamaSupplier.getText().trim();
        String no_telepon = txtNomorTelepon.getText().trim();
        String alamat = txtAlamat.getText().trim();

        if (id_member.isEmpty() || nama_member.isEmpty() || alamat.isEmpty() 
                || no_telepon.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua Kolom Harus Di-isi", 
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String sql = "INSERT INTO supplier (id_supplier, nama_supplier, no_telepon, alamat) "
                    + "VALUES (?, ?, ?, ?)";
            try (PreparedStatement st = conn.prepareStatement(sql)) {
                st.setString(1, id_member);
                st.setString(2, nama_member);
                st.setString(3, no_telepon);
                st.setString(4, alamat);

                int rowInserted = st.executeUpdate();
                if (rowInserted > 0) {
                    // Notifikasi sukses
                    JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan", 
                            "Sukses", JOptionPane.INFORMATION_MESSAGE);

                    resetForm();
                    dispose();
                }
            }
        } catch (Exception e) {
            Logger.getLogger(tambahSupplier.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
    private void updateData() {
        String id_supplier = txtIdSupplier.getText();
        String nama_supplier = txtNamaSupplier.getText();
        String no_telepon = txtNomorTelepon.getText();
        String alamat = txtAlamat.getText();
        
        
        if (id_supplier.isEmpty() || nama_supplier.isEmpty() || alamat.isEmpty() 
                || no_telepon.isEmpty()) {
            // Menggunakan JOptionPane untuk menampilkan pesan peringatan
            JOptionPane.showMessageDialog(this, "Semua Kolom Harus Di-isi", 
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            String sql = "UPDATE supplier SET nama_supplier=?, no_telepon=?, alamat=? "
                    + "WHERE id_supplier=?";
            try(PreparedStatement st = conn.prepareStatement(sql)){
                st.setString(1, nama_supplier);
                st.setString(2, no_telepon);
                st.setString(3, alamat);
                st.setString(4, id_supplier);

                
                int rowInserted = st.executeUpdate();
                if (rowInserted > 0) {
                    // Notifikasi sukses
                    JOptionPane.showMessageDialog(this, "Data Berhasil Diubah", 
                            "Sukses", JOptionPane.INFORMATION_MESSAGE);

                    resetForm();
                    dispose();
                }
            }
        } catch (Exception e) {
            Logger.getLogger(tambahSupplier.class.getName()).log(Level.SEVERE, null, e);
        }
    }

}


