package bareSkinMenu;

import bareSkinLogin.loginBareSkin;
import config.koneksi;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


public class tambahKaryawan extends javax.swing.JDialog {
    
    private int halamanSaatIni = 1;
    private int dataPerHalaman = 14;
    private int totalPages;
    private Connection conn;
    
    private String id_user;
    private String nama;
    private String alamat;
    private String username;
    private String password;
    private String level;
    
    public String getId_user() {
        return id_user;
    }

    public String getNama() {
        return nama;
    }
    
    public String getAlamat() {
        return alamat;
    }

    public String getUsername() {
        return username;
    }

    public String getPassword() {
        return password;
    }
    
    public String getLevel() {
        return level;
    }

    public tambahKaryawan(java.awt.Frame parent, boolean modal, String id, 
            String nama, String alamat, String username, String password) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        conn = koneksi.getConnection();

        this.id_user = id;
        this.nama = nama;
        this.alamat = alamat;
        this.username = username;
        this.password = password;

        txtIdKaryawan.setText(id);
        txtNamaKaryawan.setText(nama);
        txtAlamat.setText(alamat);
        txtUsername.setText(username);
        txtPassword.setText(password);
        btnSimpan.setText("SIMPAN");

        if (!txtIdKaryawan.getText().trim().isEmpty()) {
            btnSimpan.setText("UBAH");
            txtIdKaryawan.setEnabled(false);
            fieldColor(txtIdKaryawan);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelView = new javax.swing.JPanel();
        databahan = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtIdKaryawan = new custom.JTextFieldRounded();
        jLabel23 = new javax.swing.JLabel();
        txtAlamat = new custom.JTextFieldRounded();
        txtNamaKaryawan = new custom.JTextFieldRounded();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtPassword = new custom.JTextFieldRounded();
        txtUsername = new custom.JTextFieldRounded();
        jLabel32 = new javax.swing.JLabel();
        btnSimpan = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelView.setBackground(new java.awt.Color(255, 255, 255));
        panelView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        databahan.setBackground(new java.awt.Color(75, 22, 76));
        databahan.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        databahan.setForeground(new java.awt.Color(75, 22, 76));
        databahan.setText("TAMBAH KARYAWAN");
        panelView.add(databahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jLabel22.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel22.setText("ID Karyawan");
        panelView.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        txtIdKaryawan.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txtIdKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdKaryawanActionPerformed(evt);
            }
        });
        panelView.add(txtIdKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 190, 50));

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel23.setText("Nama Karyawan");
        panelView.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        txtAlamat.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        panelView.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 430, 50));

        txtNamaKaryawan.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        panelView.add(txtNamaKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 270, 50));

        jLabel28.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel28.setText("Password");
        panelView.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, -1));

        jLabel31.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel31.setText("Username");
        panelView.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, -1, -1));

        txtPassword.setText("sahur");
        txtPassword.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        panelView.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 360, -1));

        txtUsername.setText("tungtungtung");
        txtUsername.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        panelView.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 360, -1));

        jLabel32.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel32.setText("Alamat");
        panelView.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        btnSimpan.setBackground(new java.awt.Color(75, 22, 76));
        btnSimpan.setText("SIMPAN");
        btnSimpan.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        panelView.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 170, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelView, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelView, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if(btnSimpan.getText().equals("SIMPAN"))
            {
                insertData();
            }
        else if(btnSimpan.getText().equals("UBAH"))
            {
                updateData();
            }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtIdKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdKaryawanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btnSimpan;
    private javax.swing.JLabel databahan;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel panelView;
    private custom.JTextFieldRounded txtAlamat;
    private custom.JTextFieldRounded txtIdKaryawan;
    private custom.JTextFieldRounded txtNamaKaryawan;
    private custom.JTextFieldRounded txtPassword;
    private custom.JTextFieldRounded txtUsername;
    // End of variables declaration//GEN-END:variables

    private void fieldColor(JTextField field) {
        field.setOpaque(true);
        field.setEditable(false);
        field.setBackground(new Color(219, 219, 219));
    }
    
    private void resetForm() {
        txtIdKaryawan.setText("");
        txtNamaKaryawan.setText("");
        txtAlamat.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
    }
    
    public String getMd5java(String message){
        String digest = null;
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] hash = md.digest(message.getBytes("UTF-8"));
            
            StringBuilder sb = new StringBuilder( 2 * hash.length);
            for(byte b : hash){
                sb.append(String.format("%02x", b & 0xff));
            }
            digest = sb.toString();
            
        }catch (Exception e) {
            Logger.getLogger(tambahKaryawan.class.getName()).log(Level.SEVERE,null, e);
        }
        
        return digest;
    }
    
    private void insertData() {
        String id_user = txtIdKaryawan.getText().trim();
        String nama = txtNamaKaryawan.getText().trim();
        String alamat = txtAlamat.getText().trim();
        String username = txtUsername.getText().trim();
        String password = txtPassword.getText().trim();

        if (id_user.isEmpty() || nama.isEmpty() || alamat.isEmpty() 
                || username.isEmpty() || password.isEmpty()) {
            // Menggunakan JOptionPane untuk menampilkan pesan peringatan
            JOptionPane.showMessageDialog(this, "Semua Kolom Harus Di-isi", 
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String sql = "INSERT INTO user (id_user, nama, alamat, username, password, level) "
                    + "VALUES (?, ?, ?, ?, ?, ?)";
            try (PreparedStatement st = conn.prepareStatement(sql)) {
                st.setString(1, id_user);
                st.setString(2, nama);
                st.setString(3, alamat);
                st.setString(4, username);
                st.setString(5, getMd5java(password));
                st.setString(6, "Kasir");

                int rowInserted = st.executeUpdate();
                if (rowInserted > 0) {
                    // Notifikasi sukses
                    JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan", 
                            "Sukses", JOptionPane.INFORMATION_MESSAGE);

                    resetForm();
                    dispose();
                }
            }
        } catch (Exception e) {
            Logger.getLogger(tambahKaryawan.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void updateData() {
        String id_user = txtIdKaryawan.getText();
        String nama = txtNamaKaryawan.getText();
        String alamat = txtAlamat.getText();
        String username = txtUsername.getText();
        String password = txtPassword.getText();

        if (id_user.isEmpty() || nama.isEmpty() || alamat.isEmpty() 
                || username.isEmpty() || password.isEmpty()) {
            // Menggunakan JOptionPane untuk menampilkan pesan peringatan
            JOptionPane.showMessageDialog(this, "Semua Kolom Harus Di-isi", 
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            String sql = "UPDATE user SET nama=?, alamat=?, username=?, password=? "
                    + "WHERE id_user=?";
            try(PreparedStatement st = conn.prepareStatement(sql)){
                st.setString(1, nama);
                st.setString(2, alamat);
                st.setString(3, username);
                st.setString(4, getMd5java(password));
                st.setString(5, id_user);

                
                int rowInserted = st.executeUpdate();
                if (rowInserted > 0) {
                    // Notifikasi sukses
                    JOptionPane.showMessageDialog(this, "Data Berhasil Diubah", 
                            "Sukses", JOptionPane.INFORMATION_MESSAGE);

                    resetForm();
                    dispose();
                }
            }
        } catch (Exception e) {
            Logger.getLogger(tambahKaryawan.class.getName()).log(Level.SEVERE, null, e);
        }
    }
}
